### PR TITLE
Manipulate[]

### PR DESCRIPTION
**Pull request by poke1024**
Ports Manipulate[] into the new combined IMathics/Mathics branch. Depends on https://github.com/mathics/Mathics/pull/480 and https://github.com/mathics/IMathics/pull/11.

### CODE REVIEW

**Comment by poke1024** [comment]
Travis fails are due to https://github.com/mathics/Mathics/pull/480 not yet available.

**Comment by sn6uv** [comment]
Is this the last of the changes to be ported over from the `imathics` branch?

**Comment by poke1024** [comment]
Yes, this is the last one.

**Comment by sn6uv** [comment]
Great! I've deleted the `imathics` branch now.

**Pull request merged**
