### PR TITLE
Update to Django 2.2

### PR DESCRIPTION
**Pull request by GarkGarcia**
This is a follow up to #879.

### CODE REVIEW

**Comment by GarkGarcia** [comment]
This has been helpful: https://docs.djangoproject.com/en/3.1/releases/1.10/

**Comment by GarkGarcia** [comment]
@rocky @mmatera I have no experience with Django, could you guys help me out? The tests are passing and `mathicsserver` isn't crashing, but this is all I get:

Screenshot from 2020-09-17 16-20-05

**Comment by GarkGarcia** [comment]
> @rocky @mmatera I have no experience with Django, could you guys help me out? The tests are passing and `mathicsserver` isn't crashing, but this is all I get:
> 
> Screenshot from 2020-09-17 16-20-05

Sorry about that, that had nothing to do with the update. It turns out my Django installation was corrupted.

**Comment by GarkGarcia** [comment]
Ok, now `mathicsserver` doesn't crash but it hangs indefinitely... The page simply never loads.

**Comment by mmatera** [comment]
That's the problem to maintain the graphic interface and the kernel in the same project: tests of one thing and the other do not have anything to do between each other. We should think about possible tests to check mathicsserver.

**Comment by GarkGarcia** [comment]
For some reason the server fails to serve some relevant JS files:

```
Mathics 1.1.dev0
on CPython 3.6.9 (default, Jul 17 2020, 12:50:27)
using SymPy 1.6.2, mpmath 1.1.0, django 2.2

Copyright (C) 2011-2020 The Mathics Team.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.
See the documentation for the full license.

Quit by pressing CONTROL-C

Open the graphical user interface at
http://localhost:8000
in Firefox, Chrome, or Safari to use Mathics

loading symbols
[17/Sep/2020 23:03:58] "GET / HTTP/1.1" 200 10726
[17/Sep/2020 23:03:58] "GET /media/css/message.css HTTP/1.1" 200 722
[17/Sep/2020 23:03:58] "GET /media/js/mathjax/MathJax.js?config=MML_HTMLorMML&delayStartupUntil=configured HTTP/1.1" 304 0
[17/Sep/2020 23:03:58] "GET /media/js/message.js HTTP/1.1" 304 0
[17/Sep/2020 23:03:58] "GET /media/js/authentication.js HTTP/1.1" 304 0
[17/Sep/2020 23:03:58] "GET /media/js/inout.js HTTP/1.1" 304 0
[17/Sep/2020 23:03:58] "GET /media/js/utils.js HTTP/1.1" 304 0
[17/Sep/2020 23:03:58] "GET /media/js/mathics.js HTTP/1.1" 304 0
[17/Sep/2020 23:03:58] "GET /media/js/graphics3d.js HTTP/1.1" 304 0
[17/Sep/2020 23:03:58] "GET /media/js/doc.js HTTP/1.1" 304 0
[17/Sep/2020 23:03:58] "GET /media/js/scriptaculous/builder.js HTTP/1.1" 304 0
[17/Sep/2020 23:03:58] "GET /media/js/scriptaculous/effects.js HTTP/1.1" 304 0
[17/Sep/2020 23:03:58] "GET /media/js/scriptaculous/dragdrop.js HTTP/1.1" 304 0
[17/Sep/2020 23:03:58] "GET /media/js/scriptaculous/controls.js HTTP/1.1" 304 0
[17/Sep/2020 23:03:58] "GET /media/js/scriptaculous/slider.js HTTP/1.1" 304 0
[17/Sep/2020 23:03:58] "GET /media/js/scriptaculous/sound.js HTTP/1.1" 304 0
```

Also, for some reason the page sort of loads just after I shutdown the server. @mmatera @rocky Could you guys try running the server on your machines?

**Comment by GarkGarcia** [comment]
Everything is working locally now (although I'm not sure why it didn't work before). I'll merge the PR if no tests fail.

**Comment by GarkGarcia** [comment]
> That's the problem to maintain the graphic interface and the kernel in the same project: tests of one thing and the other do not have anything to do between each other. We should think about possible tests to check mathicsserver.

I agree. We should at least test if `mathicsserver` fails to load the main page.

**Pull request merged**
