### PR TITLE
Fix #989

### LINKED ISSUE #989: Parser can't differentiate between ReplaceAll and Division
Take a look at this example.

Mathics:

```julia
In[1]:= 1/.2
ReplaceAll::reps: 2 is not a valid replacement rule.
Out[1]= 1 /. 2
```

Wolfram:

image
image

Not really a big problem, but is something that needs to be fixed eventually.

### PR DESCRIPTION
**Pull request by mmatera**
This is a more elegant way to fix #989 than #990

### CODE REVIEW

**Comment by rocky** [comment]
I think you have to use  mark a lookahead, i.e. `(?<= ...)` somehow.

**Comment by mmatera** [comment]
You are right! I hope now it works...

**Comment by mmatera** [comment]
So, the unique thing that deserves revision is the test in the docstring. @rocky, if you agree, I merge this.

**Comment by rocky** [comment]
If you ask my opinion, for an example it would need more explanation in the example. 
That casually this looks like it might be `ReplaceAll[]` for example if this were `/.x` instead of `/.2`. 

Otherwise I think it would be better done as a test in `test/test_evaluation.py` because  `a /.5 == 2 a` isn't all that interesting in of itself. 

Your choice though. 

And feel free to merge whenever you like.

**Pull request merged**
