### PR TITLE
More descriptive and general in prep for profiling

### PR DESCRIPTION
**Pull request by rocky**
Memoization isn't haven't a big effect although I do see it is doing something. More important from a maintainablilty

is the blackening of some files and clearification with by starting to rename `apply_2`, etc with more descriptive name and to use
"%(name)s" so that when things move around we don't have to change that.

### CODE REVIEW

**Comment by mmatera** [comment]
@rocky, about memoization, the kernel has already implemented an expression cache, in a way that if you call several times the same (mpmath/numpy/whatever) function, the result is read from a lookup table instead of calling apply_ methods.

**Comment by mmatera** [comment]
With the blackening, and using more descriptive names, I completely agree.

**Comment by rocky** [comment]
> about memoization, the kernel has already implemented an expression cache, in a way that if you call several times the same (mpmath/numpy/whatever) function, the result is read from a lookup table instead of calling apply_ methods.

@mmatera - Let me check this by timing... 

Without: 
```
In[1]:= Timing[RealDigits[Pi, 10, 1, -10000]]
Out[1]= {4.51084, {{8}, -9999}}

In[2]:= Timing[RealDigits[Pi, 10, 1, -10000]]
Out[2]= {6.65212, {{8}, -9999}}
```

with: 
```In[1]:= Timing[RealDigits[Pi, 10, 1, -10000]]
Out[1]= {4.50568, {{8}, -9999}}

In[2]:= Timing[RealDigits[Pi, 10, 1, -10000]]
Out[2]= {3.432, {{8}, -9999}}
```

Please doublecheck though...

**Comment by mmatera** [comment]
> > about memoization, the kernel has already implemented an expression cache, in a way that if you call several times the same (mpmath/numpy/whatever) function, the result is read from a lookup table instead of calling apply_ methods.
> 
> @mmatera - Let me check this by timing...
> 
> Without:
> 
> ```
> In[1]:= Timing[RealDigits[Pi, 10, 1, -10000]]
> Out[1]= {4.51084, {{8}, -9999}}
> 
> In[2]:= Timing[RealDigits[Pi, 10, 1, -10000]]
> Out[2]= {6.65212, {{8}, -9999}}
> ```
> 
> with:
> 
> ```
> Out[1]= {4.50568, {{8}, -9999}}
> 
> In[2]:= Timing[RealDigits[Pi, 10, 1, -10000]]
> Out[2]= {3.432, {{8}, -9999}}
> ```
> 
> Please doublecheck though...

OK, looks appealing. However, this seems to indicate that the expression cache is not working properly...
This weekend I'm a little busy. I can look at this over the next week.

**Comment by rocky** [comment]
> However, this seems to indicate that the expression cache is not working properly...
> This weekend I'm a little busy. I can look at this over the next week.

No problem. There is a lot of evidence to suggest that caching at a higher level would be a big win. 

Possibliy related by possibily different: CProfile data suggests that most of the time is spent higher up such as in pattern matching. If that is so, caching at a higher level would be a big win. Alternatively there's probably somehting at the pattern matching that could be done to speed things up, but  I haven't been able to get the right level of granularity in pattern.py:394 `match_leaf()`  to understand what's up.

**Review by mmatera — APPROVED** [review]
LGTM

**Comment by rocky** [comment]
@mmatera We should merge this and continue with other performance efforts, right?

**Comment by mmatera** [comment]
> @mmatera We should merge this and continue with other performance efforts, right?

Yes, I think that the changes here help and do not hurt future improvements. I would focus the efforts on the ExpressionCache before tackling specific things like numerics.

**Pull request merged**
