### PR TITLE
Update CHANGES.rst

### PR DESCRIPTION
**Pull request by rocky**
Run "make ChangeLog", look at the output and then add to CHANGES.rst

Note: this is intended to be a _summary_ of all the changes, not a blow by blow description.  So it is sufficient to mention that some files were blacken formatted once rather than for every time it was done. 

Often a feature is added and then fixed several times. From the standpoint of the user, all that matters is that the feature was added. 

Administrative items such as fixing CI endlessly, I don't think those need to be mentioned.

### CODE REVIEW

**Comment by GarkGarcia** [comment]
@rocky Do you consider this to be finished? It looks like `CHANGES.rst` is up-to-date now.

**Comment by GarkGarcia** [comment]
There are some bug fixes that come to mind which are not mentioned in `CHANGES.rst`, such as https://github.com/mathics/Mathics/issues/795. @rocky Could I push a commit to your branch?

**Comment by rocky** [comment]
Pluse amend as you see fit. This is just a start. Undoubtably there will be more updates.

**Comment by GarkGarcia** [comment]
I couldn't find any other issue/feature that wasn't mentioned in `CHANGES.rst`. @rocky I guess we're done with this commit? We should enforce the practice of logging changes introduced by PRs before we merge them, but I'm not sure how this could be done.

**Comment by rocky** [comment]
I think done for now. There will be updates in the future,. but this gets us closer to reducing the work for a release.

I don't know of an automated practice for summarizing and making sure that PR's get added. It could be added as part of some sort of developer process or contributing guide. 

But now that this is relatively up to date, as PR's get merged the PR should include a change to CHANGES if it is relevant.

**Comment by GarkGarcia** [comment]
> as PR's get merged the PR should include a change to CHANGES if it is relevant

Yes. That's what I meant by _"We should enforce the practice of logging changes introduced by PRs before we merge them"_. Maybe we could somehow test this? The problem with that is that there are PRs which shouldn't be mentioned in `CHANGES.rst`.

I'll merge the PR for now.

**Pull request merged**
