### PR TITLE
Nintegrate rebased

### PR DESCRIPTION
**Pull request by rocky**
A rebase of #1160 

There were also some commits squashed, small revisions to `CHANGES.rst` (e.g. make it consistent with prior formatting), some things that Python linting caught. 

@mmatura I generally merged HEAD over what was in master, although in some cases it looked like master had advanced. 

The thing I am most unsure about is that tagging difference between compiled code and compled functions. So please review.

### CODE REVIEW

**Comment by mmatera** [comment]
I merged master in #1160, and on the top of this, I pass black and pyflakes. Then I took some lines from this PR correcting some errors. Then I compared it with this one. So, from the original branch I would keep:
* compilation.py, I tagged different llvmlite and Python non compiled code in the makeboxes as `-CompileCode-` and `-PythonizedCode-`. This is not in this  branch.
* I blacked functional.py
* I keep some  print  warnings in numeric.py

**Comment by rocky** [comment]
@mmatera I am not sure I understand the details, but what to do is clearer:

close one of the PR's and merge the other. 

One thing that keeps happening that confuses a lot of this is that there are changes outside of the stated intent. In particular Nintegrate incorporates compile function changes and this make tracking changes more difficult.  Both PR's have updates to CHANGES.rst which go beyond what is in Nintegrate as well.

**Comment by mmatera** [comment]
> @mmatera I am not sure I understand the details, but what to do is clearer:
> 
> Please close one of the PR's and merge into master the other.
> 
> One thing that keeps happening that confuses a lot of this is that there are changes outside of the stated intent. In particular Nintegrate incorporates compile function changes and this make tracking changes more difficult. Both PR's have updates to CHANGES.rst which go beyond what is in Nintegrate as well.
Sorry about that. The problem is that many times, trying to implement a fix, a secondary issue appears, and then the thing starts to diverge.

**Comment by mmatera** [comment]
Changes incorporated in #1160.

**Pull request closed without merging**
