### PR TITLE
Create cuboid3dbox

### PR DESCRIPTION
**Pull request by rocky**

### CODE REVIEW

**Comment by rocky** [comment]
@TiagoCavalcanteTrindade I believe the pattern-matching for Cuboid is now as expected. But see if this now does what you expect.

**Comment by rocky** [comment]
One other thing needs to be noted: Mathematica allows Cuboid as a 2D object as well as a 3D object. I don't believe that is handled properly here.

**Comment by rocky** [comment]
```
Graphics3D[Cuboid[{0, 0, 1}]] // TeXForm
```

gives 

```
System::exception:

Exception raised: name 'l' is not defined
Traceback (most recent call last):
File "/src/external-vcs/github/Mathics3/mathics-django/mathics_django/web/views.py", line 588, in query result = evaluation.evaluate(expr, timeout=TIMEOUT) 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/evaluation.py", line 361, in evaluate result = run_with_timeout_and_stack(evaluate, timeout, self) 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/evaluation.py", line 118, in run_with_timeout_and_stack return request() 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/evaluation.py", line 354, in evaluate return self.format_output(self.last_eval, format) 
File "/src/external-vcs/github/Mathics3/mathics-django/mathics_django/web/models.py", line 33, in <lambda> evaluation, expr, format 
File "/src/external-vcs/github/Mathics3/mathics-django/mathics_django/web/format.py", line 83, in format_output result = Expression("StandardForm", expr).format(obj, "System`TeXForm") 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/expression.py", line 523, in format result = Expression("MakeBoxes", expr, Symbol(form)).evaluate(evaluation) 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/expression.py", line 1315, in evaluate expr, reevaluate = expr.evaluate_next(evaluation) 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/expression.py", line 1449, in evaluate_next result = rule.apply(new, evaluation, fully=False) 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/rules.py", line 67, in apply self.pattern.match(yield_match, expression, {}, evaluation, fully=fully) 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/pattern.py", line 291, in match self.head.match(yield_head, expression.get_head(), vars, evaluation) 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/pattern.py", line 159, in match yield_func(vars, None) 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/pattern.py", line 282, in yield_head yield_choice, expression, attributes, head_vars 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/pattern.py", line 429, in get_pre_choices yield_func(vars) 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/pattern.py", line 270, in yield_choice wrap_oneid=expression.get_head_name() != "System`MakeBoxes", 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/pattern.py", line 661, in match_leaf include_flattened=include_flattened, 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/pattern.py", line 456, in get_wrappings yield_func(items[0]) 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/pattern.py", line 652, in yield_wrapping wrap_oneid=wrap_oneid, 
File "/src/external-vcs/github/mathics/Mathics/mathics/builtin/patterns.py", line 852, in match self.pattern.match(yield_func, expression, new_vars, evaluation) 
File "/src/external-vcs/github/mathics/Mathics/mathics/builtin/patterns.py", line 1050, in match yield_func(vars, None) 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/pattern.py", line 636, in match_yield wrap_oneid=wrap_oneid, 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/pattern.py", line 661, in match_leaf include_flattened=include_flattened, 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/pattern.py", line 456, in get_wrappings yield_func(items[0]) 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/pattern.py", line 652, in yield_wrapping wrap_oneid=wrap_oneid, 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/pattern.py", line 159, in match yield_func(vars, None) 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/pattern.py", line 640, in match_yield yield_func(new_vars, items_rest) 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/pattern.py", line 618, in leaf_yield (list(chain(rest_expression[0], items_rest[0])), next_rest[1]), 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/rules.py", line 42, in yield_match new_expression = self.do_replace(expression, vars, options, evaluation) 
File "/src/external-vcs/github/mathics/Mathics/mathics/core/rules.py", line 131, in do_replace return self.function(evaluation=evaluation, **vars_noctx) 
File "/src/external-vcs/github/mathics/Mathics/mathics/builtin/inout.py", line 2083, in apply_tex tex = boxes.boxes_to_tex(evaluation=evaluation) 
File "/src/external-vcs/github/mathics/Mathics/mathics/builtin/box/graphics3d.py", line 415, in boxes_to_tex asy = format_fn(elements) 
File "/src/external-vcs/github/mathics/Mathics/mathics/format/asy.py", line 327, in graphics_elements result.append(format_fn(element)) 
File "/src/external-vcs/github/mathics/Mathics/mathics/format/asy.py", line 215, in cuboid3dbox stroke_width=l, NameError: name 'l' is not defined</lambda>
```

**Comment by TiagoCavalcanteTrindade** [comment]
> One other thing needs to be noted: Mathematica allows Cuboid as a 2D object as well as a 3D object. I don't believe that is handled properly here.

No, it isn't.

About the exception, I created a PR that solves it.

**Comment by rocky** [comment]
> > One other thing needs to be noted: Mathematica allows Cuboid as a 2D object as well as a 3D object. I don't believe that is handled properly here.
> 
> No, it isn't, but `Rectangle` does that.
> 
> About the exception, I created a PR that solves it.

@TiagoCavalcanteTrindade A link to the PR?

**Pull request merged**
