### PR TITLE
Improved worksheet management

### PR DESCRIPTION
**Pull request by suhr**
Fork of https://github.com/mathics/Mathics/pull/695

### CODE REVIEW

**Comment by wolfv** [comment]
let me know once this is done!

**Comment by wolfv** [comment]
is there a version of this that i should merge?

**Comment by wolfv** [comment]
@suhr is this one ready to go in? I think making a release soon would be cool!

**Comment by suhr** [comment]
No. In fact I should have closed this in favor of #695.

**Pull request closed without merging**
