### PR TITLE
Fix ajax requests

### PR DESCRIPTION
**Pull request by suhr**

### CODE REVIEW

**Review by rocky — COMMENTED** [review]
Thanks! Will check over now and merge when CI finishes.

**Comment by suhr** [comment]
By the way, is there a way to install Mathics with documentation without building PDF docs? I don't want to install LaTeX.

**Comment by suhr** [comment]
Also, we really should use f-strings everywhere.

**Comment by rocky** [comment]
> By the way, is there a way to install Mathics with documentation without building PDF docs? I don't want to install LaTeX.

I am not 100% sure, but try `make mathics/doc/tex/data`. If you have [`remake`](https://remake.readthedocs.io/en/latest/features.html) installed, you might be able to see this by running `remake --tasks`. 

The make command expands to:

```
python mathics/test.py -o
```

After a 1.1 release the way documentation and testing is done really needs to be rethought and redone using current 2020 practice.

**Comment by rocky** [comment]
@suhr  Unless you have more changes, let's get this in.

**Comment by suhr** [comment]
Sure, feel free to merge this.

**Pull request merged**
