### PR TITLE
Improve Range performance a bit

### PR DESCRIPTION
**Pull request by TiagoCavalcanteTrindade**

### CODE REVIEW

**Comment by rocky** [comment]
How does one see  what improvement is gained by this?

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky I removed a function call.

**Comment by rocky** [comment]
> @rocky I removed a function call.

Whey do we think that the conversion from sympy call isn't needed?

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky ok, this makes sense.

**Pull request closed without merging**
