### PR TITLE
Changes for imathics kernel

### PR DESCRIPTION
**Pull request by poke1024**
I strongly suggest we merge the changes necessary to run Mathics as an imathics kernel into `master`. The current imathics branch is outdated and it's a pain to keep it updated. This is a proposal to add all necessary changes to master.

I've tested this with the experimental version in https://github.com/mathics/IMathics/pull/11 under Jupyter 5.

### CODE REVIEW

**Comment by sn6uv** [comment]
Great idea

**Comment by poke1024** [comment]
Done.

Basically two changes:

(1) the callbacks in `Evaluation` are now gathered in a single class `Output`
(2) all image outputs (i.e. svgs, imgs) now output `mglyphs`

(2) has the advantage of working with Jupyter without additional JavaScript transformations. On the other hand, in order to not break any behaviours in the classic Mathics web frontend, I added JS code to convert `mglyph` to `svg` or `img`, so that there's really no change for the frontend JS logic.

I'm not sure about the max_allowed_packet size, which was changed in the imathics branch. Is it something that should always be unlimited for Jupyter kernels?

**Comment by sn6uv** [comment]
I was running into trouble with the `max_allowed_packet_size` when working with large images. I don't remember exactly what it was sorry.

**Comment by sn6uv** [comment]
This is breaking plots on Firefox for me.

**Comment by poke1024** [comment]
I cannot reproduce this using Firefox 48.0.1 under OS X; I added a `svg.setAttribute('data-info', 'generated through convertMathGlyphs()');` in `web/media/js/mathics.js:convertMathGlyphs()` to make sure I really tested the code, but it ends up in my Firefox (see attached image) and it works. Which OS/Firefox versions are you using? Any extensions? JavaScript is enabled?
firefox

**Comment by sn6uv** [comment]
Cleared my cache and it seems to be fixed now. Not sure what the problem was, half of the SVG wasn't present in the HTML document.

**Comment by poke1024** [comment]
Maybe the new JavaScript didn't get loaded properly.

**Pull request merged**
