### PR TITLE
Don't use p/q of Rational + import cleanup

### PR DESCRIPTION
**Pull request by skirpichev**
Hello,

I did [some work](https://github.com/skirpichev/Mathics/tree/diofant-experiment) to make Mathcis codebase working on a different CAS kernel, the [Diofant](https://github.com/diofant/diofant).  To my surprise, it works quite well (test pass locally) and required changes are small.

Not sure if Mathics developers will be positive on making Python CAS backend swichable, but here some simple fixes from the mentioned branch. I hope, this could be useful on its own.

### CODE REVIEW

**Comment by skirpichev** [comment]
Rebased on top of recent master.  Now tests pass.

**Comment by wolfv** [comment]
Hi @skirpichev are you ok with rebasing the changes on master and squashing the commits?

**Comment by skirpichev** [comment]
Hmm, now there are test failures.

**Comment by wolfv** [comment]
Yes, those are unrelated to your changes. I'll try to sort out.

**Comment by skirpichev** [comment]
No errors on the master, as per travis-ci, so these may be related.  However, build is 2 months old, maybe there are new failures just due to changed requirements.

I suggest using cron jobs to trigger master builds.  This should catch such issues, as you merge pull requests not too often.

**Comment by wolfv** [comment]
I just fixed the travis bug. feel free to rebase once more!

**Comment by skirpichev** [comment]
On Wed, May 15, 2019 at 05:42:35AM -0700, Wolf Vollprecht wrote:
>    I just fixed the travis bug. feel free to rebase once more!

Done.

**Comment by skirpichev** [comment]
Tests pass.

**Comment by suhr** [comment]
Looks good to me (I'm not really a python programmer though).

**Comment by skirpichev** [comment]
Rebased again.

**Pull request merged**
