### PR TITLE
Replace `Expression(N, ...).evaluate(...)` by `apply_N(...)`

### PR DESCRIPTION
**Pull request by TiagoCavalcante**
I hope this doesn't delay the transference. I just made this now because this is small.

### CODE REVIEW

**Comment by TiagoCavalcante** [comment]
@rocky could you run the actions again?

**Comment by rocky** [comment]
> @rocky could you run the actions again?

Restarted.

**Comment by TiagoCavalcante** [comment]
Should the tests take so much? :thinking:

**Comment by TiagoCavalcante** [comment]
@rocky something went wrong with the tests. It is better you cancel them before the minute quote ends.

**Comment by TiagoCavalcante** [comment]
image
Also, I saw in a log 100% without fails, it is stuck at this point.

**Comment by TiagoCavalcante** [comment]
Superseded by [mathics-core#12](https://github.com/Mathics3/mathics-core/pull/12).

**Pull request closed without merging**
