### PR TITLE
Revise docker setup instructions

### PR DESCRIPTION
**Pull request by rocky**
https://hub.docker.com/repository/docker/rockyb/mathics has a more recent docker contrainer for 1.1-dev.

The natlang module isn't built, but I don't think right now that's important. Never let perfection get in the way of progress.

Issue #927 has been created to track remaining steps.

@suhr @GarkGarcia @mmatera  If you have docker and get a chance, I'd appreciate it if you could try out the instructions to verify this works.

### CODE REVIEW

**Comment by GarkGarcia** [comment]
Cool! It would be nice if forked the repository within our organization (create an "official" repository for this). @poeschko Could you do that?

**Comment by GarkGarcia** [comment]
> @suhr @GarkGarcia @mmatera If you have docker and get a chance, I'd appreciate it if you could try out the instructions to verify this works.

I don't use docker at all, can't help with this one.

**Comment by mmatera** [comment]
> > @suhr @GarkGarcia @mmatera If you have docker and get a chance, I'd appreciate it if you could try out the instructions to verify this works.
> 
> I don't use docker at all, can't help with this one.

Me neither, sorry...

**Comment by suhr** [comment]
Ok, let me try...

**Comment by suhr** [comment]
```
Unable to find image 'rockyb:mathics' locally
docker: Error response from daemon: pull access denied for rockyb, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

**Comment by poeschko** [comment]
I could certainly create a repo – perhaps `mathics-docker`?

But just to make a deliberate decision: Should it really be a separate repo? Could it not just be a `Dockerfile` in the main `Mathics` repo? That's e.g. how [Sage](https://github.com/sagemath/sage) seems to do it (after they had a [separate repo](https://github.com/sagemath/docker-images) before).

**Comment by suhr** [comment]
@rocky Replacing `rockyb:mathics` with `rockyb/mathics` fixes the issue.

**Comment by GarkGarcia** [comment]
> But just to make a deliberate decision: Should it really be a separate repo? Could it not just be a `Dockerfile` in the main `Mathics` repo? That's e.g. how [Sage](https://github.com/sagemath/sage) seems to do it (after they had a [separate repo](https://github.com/sagemath/docker-images) before).

I agree. This should be in the main repo.

**Comment by rocky** [comment]
Ok. If someone wants to take things form here and put in the main repo, that woudl be awesome! 

(Note that there is the top-level dockerfile as well as a docker directory)

**Comment by rocky** [comment]
> @rocky Replacing `rockyb:mathics` with `rockyb/mathics` fixes the issue.

@suhr Thanks for trying and thanks for the feedback. It looks like there will be other changes, so I guess this fix will be incorporated into the other changes. 

Also on the next docker update, I'll do the additional steps to eliminate the missing natlang module message problem.

**Comment by rocky** [comment]
@poeschko I am part of the mathicsorg organiation, but apparently I don't have permission to create something new. The "Create Repository" Blue button is slightly faded out to indicate I can't push that. 

I've also updated the docker image to remove the natlang module problem. So maybe in the short term copy what's in rockyb/mathics over here and then things will be good. Or give me access to create a docker container. 

@suhr I've corrected the doc to change `:` to `-`, but of course the namespace currently is still rockyb while the docs have been updated to reflect `mathicsorg`. I am assuing that if you ignore that for now until it really gets to mathicsorg things will be fine or better than before

all - this is still a little bit hacky. The code between the docker config and the package config (and various CI's) really should be DRY'd and not duplicated.

 Probably building instructions should be updated too. Probably in the Wiki somehwere. 

However this is more time on this than I should have spent on it.

**Comment by poeschko** [comment]
I created the repo https://hub.docker.com/repository/docker/mathicsorg/mathics and gave you Admin access to it, @rocky. Let me know if there's anything else I can do.

**Comment by rocky** [comment]
> I created the repo https://hub.docker.com/repository/docker/mathicsorg/mathics and gave you Admin access to it, @rocky. Let me know if there's anything else I can do.

This worked. Thanks! 

https://hub.docker.com/r/mathicsorg/mathics how has the docker image and you should be able to `docker pull mathicsorg/mathics` or run as per the instructions in this updated README.rst.

**Comment by suhr** [comment]
Yes it works.

**Pull request merged**
