### PR TITLE
Add download from URL to Import[]

### PR DESCRIPTION
**Pull request by poke1024**
For example, you can now use:

`Import["https://blogs.nasa.gov/spacestation/wp-content/uploads/sites/240/2016/08/blog_iss048e061947.jpg"]`

### CODE REVIEW

**Comment by sn6uv** [comment]
What happens if the url doesn't exist? (i.e. 404 or other error code), or perhaps the url is invalid:
```
Import["https://blogs.nasa.gov/fake_path.jpg"]
Import["https:////"]
```

MMA wraps this stuff up into a function called `FetchURL` which might be a good idea to copy.

**Comment by sn6uv** [comment]
Looks like it's fixed on python 3 but python2 (I tested pypy) doesn't like the exception handling:

In[1]:= Import["https:////"]
Traceback (most recent call last):
  File "/home/angus/venv_pypy/bin/mathics", line 11, in <module>
    load_entry_point('Mathics', 'console_scripts', 'mathics')()
  File "/home/angus/Mathics/mathics/main.py", line 286, in main
    result = evaluation.evaluate(query, timeout=settings.TIMEOUT)
  File "/home/angus/Mathics/mathics/core/evaluation.py", line 243, in evaluate
    result = run_with_timeout(evaluate, timeout)
  File "/home/angus/Mathics/mathics/core/evaluation.py", line 63, in run_with_timeout
    return request()
  File "/home/angus/Mathics/mathics/core/evaluation.py", line 226, in evaluate
    result = query.evaluate(self)
  File "/home/angus/Mathics/mathics/core/expression.py", line 861, in evaluate
    result = result.evaluate(evaluation)
  File "/home/angus/Mathics/mathics/core/expression.py", line 861, in evaluate
    result = result.evaluate(evaluation)
  File "/home/angus/Mathics/mathics/core/expression.py", line 858, in evaluate
    result = rule.apply(new, evaluation, fully=False)
  File "/home/angus/Mathics/mathics/core/rules.py", line 73, in apply
    yield_match, expression, {}, evaluation, fully=fully)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 206, in match
    yield_head, expression.get_head(), vars, evaluation)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 135, in match
    yield_func(vars, None)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 198, in yield_head
    yield_choice, expression, attributes, head_vars)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 321, in get_pre_choices
    yield_func(vars)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 187, in yield_choice
    wrap_oneid=expression.get_head_name() != 'System`MakeBoxes')
  File "/home/angus/Mathics/mathics/core/pattern.py", line 478, in match_leaf
    include_flattened=include_flattened)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 342, in get_wrappings
    yield_func(items[0])
  File "/home/angus/Mathics/mathics/core/pattern.py", line 474, in yield_wrapping
    leaf_count=leaf_count, wrap_oneid=wrap_oneid)
  File "/home/angus/Mathics/mathics/builtin/patterns.py", line 761, in match
    self.pattern.match(yield_func, expression, new_vars, evaluation)
  File "/home/angus/Mathics/mathics/builtin/patterns.py", line 944, in match
    yield_func(vars, None)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 466, in match_yield
    leaf_count=leaf_count, wrap_oneid=wrap_oneid)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 478, in match_leaf
    include_flattened=include_flattened)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 342, in get_wrappings
    yield_func(items[0])
  File "/home/angus/Mathics/mathics/core/pattern.py", line 474, in yield_wrapping
    leaf_count=leaf_count, wrap_oneid=wrap_oneid)
  File "/home/angus/Mathics/mathics/builtin/patterns.py", line 761, in match
    self.pattern.match(yield_func, expression, new_vars, evaluation)
  File "/home/angus/Mathics/mathics/builtin/patterns.py", line 946, in match
    yield_func(vars, None)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 469, in match_yield
    yield_func(new_vars, items_rest)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 458, in leaf_yield
    (rest_expression[0] + items_rest[0], next_rest[1]))
  File "/home/angus/Mathics/mathics/core/rules.py", line 39, in yield_match
    new_expression = self.do_replace(vars, options, evaluation)
  File "/home/angus/Mathics/mathics/core/rules.py", line 131, in do_replace
    return self.function(evaluation=evaluation, **vars_noctx)
  File "/home/angus/Mathics/mathics/builtin/importexport.py", line 390, in apply
    except urllib.error.HTTPError as e:
In[1]:= Import["https:////"]
Traceback (most recent call last):
  File "/home/angus/venv_pypy/bin/mathics", line 11, in <module>
    load_entry_point('Mathics', 'console_scripts', 'mathics')()
  File "/home/angus/Mathics/mathics/main.py", line 286, in main
    result = evaluation.evaluate(query, timeout=settings.TIMEOUT)
  File "/home/angus/Mathics/mathics/core/evaluation.py", line 243, in evaluate
    result = run_with_timeout(evaluate, timeout)
  File "/home/angus/Mathics/mathics/core/evaluation.py", line 63, in run_with_timeout
    return request()
  File "/home/angus/Mathics/mathics/core/evaluation.py", line 226, in evaluate
    result = query.evaluate(self)
  File "/home/angus/Mathics/mathics/core/expression.py", line 861, in evaluate
    result = result.evaluate(evaluation)
  File "/home/angus/Mathics/mathics/core/expression.py", line 861, in evaluate
    result = result.evaluate(evaluation)
  File "/home/angus/Mathics/mathics/core/expression.py", line 858, in evaluate
    result = rule.apply(new, evaluation, fully=False)
  File "/home/angus/Mathics/mathics/core/rules.py", line 73, in apply
    yield_match, expression, {}, evaluation, fully=fully)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 206, in match
    yield_head, expression.get_head(), vars, evaluation)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 135, in match
    yield_func(vars, None)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 198, in yield_head
    yield_choice, expression, attributes, head_vars)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 321, in get_pre_choices
    yield_func(vars)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 187, in yield_choice
    wrap_oneid=expression.get_head_name() != 'System`MakeBoxes')
  File "/home/angus/Mathics/mathics/core/pattern.py", line 478, in match_leaf
    include_flattened=include_flattened)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 342, in get_wrappings
    yield_func(items[0])
  File "/home/angus/Mathics/mathics/core/pattern.py", line 474, in yield_wrapping
    leaf_count=leaf_count, wrap_oneid=wrap_oneid)
  File "/home/angus/Mathics/mathics/builtin/patterns.py", line 761, in match
    self.pattern.match(yield_func, expression, new_vars, evaluation)
  File "/home/angus/Mathics/mathics/builtin/patterns.py", line 944, in match
    yield_func(vars, None)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 466, in match_yield
    leaf_count=leaf_count, wrap_oneid=wrap_oneid)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 478, in match_leaf
    include_flattened=include_flattened)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 342, in get_wrappings
    yield_func(items[0])
  File "/home/angus/Mathics/mathics/core/pattern.py", line 474, in yield_wrapping
    leaf_count=leaf_count, wrap_oneid=wrap_oneid)
  File "/home/angus/Mathics/mathics/builtin/patterns.py", line 761, in match
    self.pattern.match(yield_func, expression, new_vars, evaluation)
  File "/home/angus/Mathics/mathics/builtin/patterns.py", line 946, in match
    yield_func(vars, None)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 469, in match_yield
    yield_func(new_vars, items_rest)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 458, in leaf_yield
    (rest_expression[0] + items_rest[0], next_rest[1]))
  File "/home/angus/Mathics/mathics/core/rules.py", line 39, in yield_match
    new_expression = self.do_replace(vars, options, evaluation)
  File "/home/angus/Mathics/mathics/core/rules.py", line 131, in do_replace
    return self.function(evaluation=evaluation, **vars_noctx)
  File "/home/angus/Mathics/mathics/builtin/importexport.py", line 390, in apply
    except urllib.error.HTTPError as e:
```

Can you add some (hidden) tests for these failing cases too?

**Comment by poke1024** [comment]
I'm not sure how to add a hidden test case. Any examples anywhere?

**Comment by sn6uv** [comment]
There should be heaps. Just put `#> Import[..]` in the docstring.

**Comment by sn6uv** [comment]
Great! I was thinking about adding a functional test (imports a valid website) but we probably don't want to rely on an internet connection for the tests to pass.

**Pull request merged**
