### PR TITLE
Jupyter

### PR DESCRIPTION
**Pull request by mmatera**
Just an interface to make Mathics to work in jupyter

### CODE REVIEW

**Comment by sn6uv** [comment]
Hi @mmatera. I think developing an IPython kernel is a great idea. It looks like the Jupyter spec has changed quite a bit recently so this code is now out of date (partly my fault for taking so long to look at it). In addition there's a bunch of extra stuff committed here.

I've started working on this myself, see my jupyter branch. I think we should develop this in a separate branch and when it's ready/stable we can merge into master.

**Comment by sn6uv** [comment]
@mmatera, I've decided to move the jupyter kernel to a separate repository mathics/IMathics. I'm planning to release Mathics 0.9 pretty soon (March 1 is the tentitive release date) and my goal is to also have a jupyter kernel to accompany the release. The kernel still lacks some features, particularly graphics support. If you're still interested in working on this I'd love to get your input/feedback.

**Comment by mmatera** [comment]
@sn6uv, about what is missing, I thing that is not too much. First of all we should fix some behaviours about latex form. then, 2d graphics are almost supported by the current version, by exporting them first as svg (I have added this functionality) and  the biggest issue would be to solve the 3d support. 
Right now, my only problem is that I will not have much time until April. But I will see if I cad do something.

Cheers

**Comment by sn6uv** [comment]
Okay, in that case maybe we can aim to have latex and 2D graphics working but defer 3D til later? If you have time great but don't stress about it. Thanks for your contribution!

**Comment by mmatera** [comment]
Yes, I think that I can manage to implement the latex and the 2D graphs support during these weeks.  About 3D, my problem is that I do not complete understand how does it work in the current implementation of mathics, but maybe it would be not so complicate to include it, if we realize how to embed the right html/javascript code in jupyter.

M

**Comment by sn6uv** [comment]
Great! I can take a look at 3D graphics. I wrote the current implementation in Mathics. The idea is simple but the implementation is a bit messy.

Here's a simple [example](http://mathics.angusgriffith.com/#cXVlcmllcz1HcmFwaGljczNEJTVCUG9seWdvbiU1QiU3QiU3QjAlMkMwJTJDMCU3RCUyQyUyMCU3QjAlMkMxJTJDMSU3RCUyQyUyMCU3QjElMkMwJTJDMCU3RCU3RCU1RCU1RA==). If you capture the ajax response there's a <graphics 3d> element in the result:

```
<graphics3d data="{&quot;viewpoint&quot;: [1.3, -2.4, 2.0], &quot;elements&quot;: [{&quot;coords&quot;: [[[0.0, 0.0, 0.0], null], [[0.0, 1.0, 1.0], null], [[1.0, 0.0, 0.0], null]], &quot;type&quot;: &quot;polygon&quot;, &quot;faceColor&quot;: [1, 1, 1, 1]}], &quot;lighting&quot;: [{&quot;color&quot;: [0.3, 0.2, 0.4], &quot;type&quot;: &quot;Ambient&quot;}, {&quot;color&quot;: [0.8, 0.0, 0.0], &quot;position&quot;: [2.0, 0.0, 2.0], &quot;type&quot;: &quot;Directional&quot;}, {&quot;color&quot;: [0.0, 0.8, 0.0], &quot;position&quot;: [2.0, 2.0, 2.0], &quot;type&quot;: &quot;Directional&quot;}, {&quot;color&quot;: [0.0, 0.0, 0.8], &quot;position&quot;: [0.0, 2.0, 2.0], &quot;type&quot;: &quot;Directional&quot;}], &quot;axes&quot;: {&quot;hasaxes&quot;: [false, false, false], &quot;ticks&quot;: [[[0.0, 0.2, 0.4, 0.6000000000000001, 0.8, 1.0], [0.05, 0.1, 0.15000000000000002, 0.25, 0.30000000000000004, 0.35000000000000003, 0.45, 0.5, 0.55, 0.65, 0.7000000000000001, 0.75, 0.8500000000000001, 0.9, 0.9500000000000001], [&quot;0.0&quot;, &quot;0.2&quot;, &quot;0.4&quot;, &quot;0.6&quot;, &quot;0.8&quot;, &quot;1.0&quot;]], [[0.0, 0.2, 0.4, 0.6000000000000001, 0.8, 1.0], [0.05, 0.1, 0.15000000000000002, 0.25, 0.30000000000000004, 0.35000000000000003, 0.45, 0.5, 0.55, 0.65, 0.7000000000000001, 0.75, 0.8500000000000001, 0.9, 0.9500000000000001], [&quot;0.0&quot;, &quot;0.2&quot;, &quot;0.4&quot;, &quot;0.6&quot;, &quot;0.8&quot;, &quot;1.0&quot;]], [[0.0, 0.2, 0.4, 0.6000000000000001, 0.8, 1.0], [0.05, 0.1, 0.15000000000000002, 0.25, 0.30000000000000004, 0.35000000000000003, 0.45, 0.5, 0.55, 0.65, 0.7000000000000001, 0.75, 0.8500000000000001, 0.9, 0.9500000000000001], [&quot;0.0&quot;, &quot;0.2&quot;, &quot;0.4&quot;, &quot;0.6&quot;, &quot;0.8&quot;, &quot;1.0&quot;]]]}, &quot;extent&quot;: {&quot;zmax&quot;: 1.0, &quot;ymax&quot;: 1.0, &quot;zmin&quot;: 0.0, &quot;xmax&quot;: 1.0, &quot;xmin&quot;: 0.0, &quot;ymin&quot;: 0.0}}" />
```

It's a bit messy because of all the HTML escaping. What we are interested in is the `data` field. Here it is unescaped:

```
{"viewpoint": [1.3, -2.4, 2.0], "elements": [{"coords": [[[0.0, 0.0, 0.0], null], [[0.0, 1.0, 1.0], null], [[1.0, 0.0, 0.0], null]], "type": "polygon", "faceColor": [1, 1, 1, 1]}], "lighting": [{"color": [0.3, 0.2, 0.4], "type": "Ambient"}, {"color": [0.8, 0.0, 0.0], "position": [2.0, 0.0, 2.0], "type": "Directional"}, {"color": [0.0, 0.8, 0.0], "position": [2.0, 2.0, 2.0], "type": "Directional"}, {"color": [0.0, 0.0, 0.8], "position": [0.0, 2.0, 2.0], "type": "Directional"}], "axes": {"hasaxes": [false, false, false], "ticks": [[[0.0, 0.2, 0.4, 0.6000000000000001, 0.8, 1.0], [0.05, 0.1, 0.15000000000000002, 0.25, 0.30000000000000004, 0.35000000000000003, 0.45, 0.5, 0.55, 0.65, 0.7000000000000001, 0.75, 0.8500000000000001, 0.9, 0.9500000000000001], ["0.0", "0.2", "0.4", "0.6", "0.8", "1.0"]], [[0.0, 0.2, 0.4, 0.6000000000000001, 0.8, 1.0], [0.05, 0.1, 0.15000000000000002, 0.25, 0.30000000000000004, 0.35000000000000003, 0.45, 0.5, 0.55, 0.65, 0.7000000000000001, 0.75, 0.8500000000000001, 0.9, 0.9500000000000001], ["0.0", "0.2", "0.4", "0.6", "0.8", "1.0"]], [[0.0, 0.2, 0.4, 0.6000000000000001, 0.8, 1.0], [0.05, 0.1, 0.15000000000000002, 0.25, 0.30000000000000004, 0.35000000000000003, 0.45, 0.5, 0.55, 0.65, 0.7000000000000001, 0.75, 0.8500000000000001, 0.9, 0.9500000000000001], ["0.0", "0.2", "0.4", "0.6", "0.8", "1.0"]]]}, "extent": {"zmax": 1.0, "ymax": 1.0, "zmin": 0.0, "xmax": 1.0, "xmin": 0.0, "ymin": 0.0}}
```

It's a json dict  describing the graphics in terms of graphics primitives. 

If you look in mathics/web/media/js/mathics.js, you'll see that it finds the `graphics3d` tag and calls `drawGraphics3D` on the `data`. The `drawGraphics3D` function is in mathics/web/media/js/graphics3d.js and uses [Three.js](http://threejs.org/) (bundled in mathics/web/media/js/three/three.js) to construct the div.

The difficult part is now, what's the best approach to get this working in Jupyter?

**Comment by sn6uv** [comment]
I figured this is something worth adding to the wiki. See https://github.com/mathics/Mathics/wiki/Graphics-3D

**Pull request closed without merging**
