### PR TITLE
Use mathics scanner release

### PR DESCRIPTION
**Pull request by rocky**
The PossibleZeroQ failure I think was a break from before and another branch may fix.

The RecursionLimit failure I'll investigate later.

### CODE REVIEW

**Comment by mmatera** [comment]
* I fixed the PossibleZeroQ in  #1145
* I restore  SingleLine.send_messages in method in mathics-scanner.feeder, get the CI passing again.

**Comment by rocky** [comment]
> * I fixed the PossibleZeroQ in  #1145

Would you please pull out the PossibleZeroQ and put that in its own PR. We'll merge that soon then

> * I restore  SingleLine.send_messages in method in mathics-scanner.feeder, get the CI passing again.

This PR addresses that. So that change can be reverted. Thanks. 

I am merging this in now. Feel free to keep commenting on it or improve it though. 

Merging in will allow mathicsscript and mathics-django to move closer to a release.

**Comment by mmatera** [comment]
> > * I fixed the PossibleZeroQ in  #1145
> 
> Would you please pull out the PossibleZeroQ and put that in its own PR. We'll merge that soon then
> 
See PR #1147

> > * I restore  SingleLine.send_messages in method in mathics-scanner.feeder, get the CI passing again.
> 
> This PR addresses that. So that change can be reverted. Thanks.
Maybe now the simple way would be to make another PR removing the method in mathics-scanner. On the other hand, wouldn't be a good idea to keep this method by now, for backward compatibility?

> 
> I am merging this in now. Feel free to keep commenting on it or improve it though.
> 
> Merging in will allow mathicsscript and mathics-django to move closer to a release.

**Comment by rocky** [comment]
See comment on that PR.

**Comment by mmatera** [comment]
regarding send_messages in mathics-scanner, you did this to avoid introduce (implicit) references to mathics in mathics-scanner?

**Comment by rocky** [comment]
Right - this was something that @GarkGarcia originally noticed. 

My goal for this weekend though is to get out a relase of whatever it is we can. If I had to do again I probably would have totally left in with the Mathics dependencies and fixed up in a later release.

However since I went down this path, best to go fix it up and now deal with backwards compatibilty of something that was never released.

**Pull request merged**
