### PR TITLE
Add Github Actions

### PR DESCRIPTION
**Pull request by suhr**

### CODE REVIEW

**Comment by suhr** [comment]
For some reason the action does not start.

**Comment by GarkGarcia** [comment]
@mmatera @rocky Any objections to this?

**Comment by mmatera** [comment]
The only objection I have is that we would need to maintain two different test schemes. But until the next release, I think we could check both and then see...

**Comment by rocky** [comment]
Let's try it. I like the dea of running both side by side to see which works better. 

One feature that Travis CI has that we are not using is that it can test MacOSX. (I use [Appveyor](https://www.appveyor.com/) to test on Windows, but it looks like it *also* works for MacOSX.

One reason CI takes so long is that we are running many simultainous tests. One way that Open Source projects increase parallelism is by running on different CI platforms (in parallel). So the doc testing could be done on say CircleCI or Github Actions if that is faster).

**Pull request merged**
