### PR TITLE
Rebase of Fix quadratic runtimes in Mathics (#619)

### PR DESCRIPTION
**Pull request by mmatera**
rebase (and a lot of fixings) of  #619

### CODE REVIEW

**Comment by rocky** [comment]
This is fantastic! Please give me a couple of days to look this over in more detail. Thanks!

**Comment by mmatera** [comment]
Do not hurry: it was sleeping for 3 years and could wait a few days more...

**Comment by rocky** [comment]
@mmatera  I think I added the merge conflict with a recent commit from one of the PRs. I'm sorry. If you have the time would you rebase this? 

Also, since you are a member it would be great if you worked off of a branch in _this_ repository rather than the mmatera fork. (The branch name could be the same name though). That makes it easier for others who have access to try the code out and fix on top of the branch. 

Again, sorry for the additional work. Thanks!

**Comment by mmatera** [comment]
I think I have fixed this in the qtime branch of this repository. I will close this PR and I invite you to look at that branch.

**Pull request closed without merging**
