### PR TITLE
Add Cylinder

### PR DESCRIPTION
**Pull request by rocky**
Apparently even the way old version of Three.js we have supports cylinders. 

There will be a change on the Mathics-Django side as well. 

Haven't considered asymptote or TeX yet though. 

Feel free to just make commits on top of this.

### CODE REVIEW

**Comment by mmatera** [comment]
I wonder if it would be possible to use mathics_scanner to define parsers for Graphics/Graphics3D like expressions. Then, it would be helpful to update or define new backends...

**Comment by rocky** [comment]
> I wonder if it would be possible to use mathics_scanner to define parsers for Graphics/Graphics3D like expressions. Then, it would be helpful to update or define new backends...

I don't understand what this means but would like to. Pretend this exists, what you then write?

**Comment by rocky** [comment]
By the way, I do think it would be nice to have a Three.js backend.

**Comment by rocky** [comment]
I am seeing a problem with Asymptote formatting of cyclinders where the bounding box starts below the base of the cylinder. However I can't figure out how to fix this. @mmatera if you can, let's fix. Otherwise let's skip.

**Comment by rocky** [comment]
I just checked the WL specification and at least to me it is weird in that from the two-argument point form you extract the length.

**Comment by mmatera** [comment]
> I just checked the WL specification and at least to me it is weird in that from the two-argument point form you extract the length.

I do not get this. Could you expand it with an example?

**Comment by rocky** [comment]
> > I just checked the WL specification and at least to me it is weird in that from the two-argument point form you extract the length.
> 
> I do not get this. Could you expand it with an example?

From https://reference.wolfram.com/language/ref/Cylinder.html : 

> Cylinder[] is equivalent to Cylinder[{{0,0,-1},{0,0,1}}].
> ... 
> Graphics3D[Cylinder[{{0, 0, 0}, {1, 1, 1}}, 1/2]]

I don't know how one orients something inside the grid box - For a sphere orientation is nonexistent. 

We need to be concerned with not just how WL takes its Cyclinder input, but pay attention to the most common definition for asymptote, Three.js and other graphics libraries that provide a cylinder. The consensus is not to do it this way, but instead have origin, radius and length. Sometimes "radius" is diameter and called "width", but the conversion from radius to width is trivial. So I think the conversion from two points to a length would be done in the Boxing routine might add minor adjustments to this.

**Comment by mmatera** [comment]
> > > I just checked the WL specification and at least to me it is weird in that from the two-argument point form you extract the length.
> > 
> > 
> > I do not get this. Could you expand it with an example?
> 
> From https://reference.wolfram.com/language/ref/Cylinder.html :
> 
> > Cylinder[] is equivalent to Cylinder[{{0,0,-1},{0,0,1}}].
> > ...
> > Graphics3D[Cylinder[{{0, 0, 0}, {1, 1, 1}}, 1/2]]
> 
> I don't know how one orients something inside the grid box - For a sphere orientation is nonexistent.
> 
> We need to be concerned with not just how WL takes its Cyclinder input, but pay attention to the most common definition for asymptote, Three.js and other graphics libraries that provide a cylinder. The consensus is not to do it this way, but instead have origin, radius and length. Sometimes "radius" is diameter and called "width", but the conversion from radius to width is trivial. So I think the conversion from two points to a length would be done in the Boxing routine might add minor adjustments to this.
 

In a 3DGraphics, you have a canonical set of coordinate orthogonal axes and a viewpoint. De default cylinder is just a cylinder of radius 1, height 2, center in the origin, and with a symmetry axis aligned with the z-axis.
Generic cylinders are defined in terms of the radius and the two central points of the corresponding tapes.  
In other graphic languages, a cylinder is first defined in terms of its radius and height, and then the object is rotated and translated. It is not hard to define a rotation that brings the z axis onto a vector v: if v is parallel to the z axis, do nothing. Otherwise, normalize de vectors   v'=v/|v|,   n=v x z/|vxz|  and m=v' x n, and build the rotation matrix R = [n m v'].
The other way is to read the spherical coordinates of v by
phi = Arg(v[[1]]+I v[[2]])
theta = ArcCos(v[[3]]/|v|)

**Comment by rocky** [comment]
> > > > I just checked the WL specification and at least to me it is weird in that from the two-argument point form you extract the length.
> > > 
> > > 
> > > I do not get this. Could you expand it with an example?
> > 
> > 
> > From https://reference.wolfram.com/language/ref/Cylinder.html :
> > > Cylinder[] is equivalent to Cylinder[{{0,0,-1},{0,0,1}}].
> > > ...
> > > Graphics3D[Cylinder[{{0, 0, 0}, {1, 1, 1}}, 1/2]]
> > 
> > 
> > I don't know how one orients something inside the grid box - For a sphere orientation is nonexistent.
> > We need to be concerned with not just how WL takes its Cyclinder input, but pay attention to the most common definition for asymptote, Three.js and other graphics libraries that provide a cylinder. The consensus is not to do it this way, but instead have origin, radius and length. Sometimes "radius" is diameter and called "width", but the conversion from radius to width is trivial. So I think the conversion from two points to a length would be done in the Boxing routine might add minor adjustments to this.
> 
> In a 3DGraphics, you have a canonical set of coordinate orthogonal axes and a viewpoint. De default cylinder is just a cylinder of radius 1, height 2, center in the origin, and with a symmetry axis aligned with the z-axis.
> Generic cylinders are defined in terms of the radius and the two central points of the corresponding tapes.
> In other graphic languages, a cylinder is first defined in terms of its radius and height, and then the object is rotated and translated. It is not hard to define a rotation that brings the z axis onto a vector v: if v is parallel to the z axis, do nothing. Otherwise, normalize de vectors v'=v/|v|, n=v x z/|vxz| and m=v' x n, and build the rotation matrix R = [n m v'].
> The other way is to read the spherical coordinates of v by
> phi = Arg(v[[1]]+I v[[2]])
> theta = ArcCos(v[[3]]/|v|)

What you say, makes sense but this is a bit more involved that I want to undertake right now. So for myself I am going to leave this be.

**Comment by mmatera** [comment]
> > > > > I just checked the WL specification and at least to me it is weird in that from the two-argument point form you extract the length.
> > > > 
> > > > 
> > > > I do not get this. Could you expand it with an example?
> > > 
> > > 
> > > From https://reference.wolfram.com/language/ref/Cylinder.html :
> > > > Cylinder[] is equivalent to Cylinder[{{0,0,-1},{0,0,1}}].
> > > > ...
> > > > Graphics3D[Cylinder[{{0, 0, 0}, {1, 1, 1}}, 1/2]]
> > > 
> > > 
> > > I don't know how one orients something inside the grid box - For a sphere orientation is nonexistent.
> > > We need to be concerned with not just how WL takes its Cyclinder input, but pay attention to the most common definition for asymptote, Three.js and other graphics libraries that provide a cylinder. The consensus is not to do it this way, but instead have origin, radius and length. Sometimes "radius" is diameter and called "width", but the conversion from radius to width is trivial. So I think the conversion from two points to a length would be done in the Boxing routine might add minor adjustments to this.
> > 
> > 
> > In a 3DGraphics, you have a canonical set of coordinate orthogonal axes and a viewpoint. De default cylinder is just a cylinder of radius 1, height 2, center in the origin, and with a symmetry axis aligned with the z-axis.
> > Generic cylinders are defined in terms of the radius and the two central points of the corresponding tapes.
> > In other graphic languages, a cylinder is first defined in terms of its radius and height, and then the object is rotated and translated. It is not hard to define a rotation that brings the z axis onto a vector v: if v is parallel to the z axis, do nothing. Otherwise, normalize de vectors v'=v/|v|, n=v x z/|vxz| and m=v' x n, and build the rotation matrix R = [n m v'].
> > The other way is to read the spherical coordinates of v by
> > phi = Arg(v[[1]]+I v[[2]])
> > theta = ArcCos(v[[3]]/|v|)
> 
> What you say, makes sense but this is a bit more involved that I want to undertake right now. So for myself I am going to leave this be.

I could take this if we have in clear how to pass a rotation to Tree.js.

**Comment by rocky** [comment]
It looks like in r49 the graphics object has a Quaternion object which has methods setFrom... methods like setFromRotationMatrix, setFromEuler, etc. See https://github.com/mrdoob/three.js/blob/r49/src/core/Quaternion.js and https://github.com/mrdoob/three.js/blob/r49/docs/api/core/Quaternion.html

**Comment by mmatera** [comment]
I was looking at this, and I see that to do this properly, we need to implement the `Transform` Builtin proposed by @poke1024.   When I have some time, I will continue with the rebase of that PR, and at least take the parts that fit here. Then, the implementation should become easier...

**Pull request closed without merging**
