### PR TITLE
fix for #331

### PR DESCRIPTION
**Pull request by sn6uv**

### CODE REVIEW

**Comment by bnjones** [comment]
If I'm reading the docs correctly, it sounds like `CompoundExpression[___, Null]` still returns `Null`, and the special case just affects the value of `Out`.

How does Mathematica treat `CompoundExpression[x, y, Null]` vs `CompoundExpression[CompoundExpression[x, y, Null], Null]`? If `Out` gets `y` in the first case and `Null` in the second, maybe it's just a special case in the evaluator which treats top-level `CompoundExpression` calls specially?

**Comment by sn6uv** [comment]
@bnjones yes, you're right. I'll fix this up.

**Comment by sn6uv** [comment]
It's actually slightly more nuanced than that: 
```mathematica
In[5]:= CompoundExpression[x, Null, Null]                       
In[6]:= Out[5]
Out[6]= x
```

**Comment by sn6uv** [comment]
Unsurprisingly there are bugs in MMA here. Evaluating the following as a single (notebook) cell:
```mathematica
1
$Line = 1
CompoundExpression[]
```

sets `Out[1]` to `1` and not `Null`

**Comment by bnjones** [comment]
Does that happen even if you take the $Line bit out?

**Comment by sn6uv** [comment]
Yes, it still does.

**Comment by bnjones** [comment]
I guess I didn't understand how evaluation in a notebook cell worked, I assumed it treated everything as one big line. Interesting find, it'd be nice if this stuff was actually documented!

**Comment by sn6uv** [comment]
Ah, my original `$Line` example was wrong (since assigning `$Line$ increments itself immediately). There's no bug here after all
```
>>> 1
    $Line = 0
    CompoundExpression[]

>>> Out[1]
     1
>>> Out[0]
    Null
```

**Comment by sn6uv** [comment]
It's quite an obscure one (but one less bug in Mathics). I guess if you're messing with `$Line$` during evaluations you're probably trying to break something in the first place.

**Pull request merged**
