### PR TITLE
implement support for sympy 1.3

### PR DESCRIPTION
**Pull request by wolfv**
Currently two tests are commented out because the way sympy returns derivatives by default seems to have changed.
It's just a cosmetic change, as it should work fine either way.

### CODE REVIEW

**Comment by wolfv** [comment]
@skirpichev @sdwfrost maybe you guys want to have a look?

@skirpichev did you fix the tests in test_conversion by any chance?

Sympy returns the derivative in a more expanded form by default now, apparently (e.g. `D[F[x, y], {x, 1}]` is now the default vs `D[F[x, y], x]` before).
Semantically it should be equivalent but might be displayed slightly different.

**Comment by skirpichev** [comment]
> @skirpichev did you fix the tests in test_conversion by any chance?

Hmm, if you are about my branch, which add Diofant support (mentioned in #745) - it doesn't break any tests in test_conversion, AFAIR.

**Comment by wolfv** [comment]
What sympy version is diofant based on?

Le 9 oct. 2018 12:46 PM, "Sergey B Kirpichev" <notifications@github.com> a
écrit :

@skirpichev <https://github.com/skirpichev> did you fix the tests in
test_conversion by any chance?

Hmm, if you are about my branch, which add Diofant support (mentioned in
#745 <https://github.com/mathics/Mathics/pull/745>) - it doesn't break any
tests in test_conversion, AFAIR.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mathics/Mathics/pull/756#issuecomment-428146256>, or mute
the thread

**Comment by skirpichev** [comment]
> What sympy version is diofant based on?

0.7.6.  But codebase was diverged drastically, much like sympy 1.3 vs 0.7.6.

**Comment by wolfv** [comment]
@skirpichev thanks, I see.

The basic issue is that with sympy 1.0 `args` yielded:

```
>>> import sympy as sp
>>> x,y,z = sp.symbols('x,y,z')
>>> sp.Derivative(sp.sin(x), x).args
(sin(x), x)
```

But with sympy 1.3 it is the more generalized form:

```
>>> sp.Derivative(sp.sin(x), x).args
(sin(x), (x, 1))
```

I guess I can write a manual translation to the Mathics form.

**Comment by wolfv** [comment]
@poeschko once we've merged this, we can add binder support to the main repository and remove mentions of the old mathics websites.

**Comment by moorepants** [comment]
> Currently two tests are commented out because the way sympy returns derivatives by default seems to have changed.

Would you mind opening an issue on SymPy about this. It could be an unintended regression.

**Comment by poeschko** [comment]
Great, thanks!

**Pull request merged**
