### PR TITLE
Improved worksheet management

### PR DESCRIPTION
**Pull request by balthild**
Demo: http://math.qaq.cat/

### CODE REVIEW

**Comment by balthild** [comment]
Could you please tell me why the build failed?
Jobs with `ALL_MODULES="true"` fail at `python: No module named requests`. Seems that `request` should be installed before build (#693), but some other PRs built successfully without this.

**Comment by larionvn** [comment]
@balthild  I'm not sure about the changing details but the TravisCI is updating its environments so it now requires more modules to run. So try to install "requests" module before build to fix your issue.

**Comment by sn6uv** [comment]
The only thing I'm not sure about is, design wise, is it best to present the users with a list of worksheets or preload one (as we do today)?

**Comment by balthild** [comment]
I agree. Displaying the worksheet last used is much better.

BTW, the sharing feature is broken. I'm fixing it.

**Comment by suhr** [comment]
I tried to rebase you PR against the current master: https://github.com/mathics/Mathics/pull/782

It runs, but /ajax/getworksheets/ throws `sqlite3.OperationalError: no such table: web_worksheet`.

Would you like to update your PR to current master branch (using django 1.11)?

**Comment by balthild** [comment]
The `/ajax/getworksheets/` route hits this function: https://github.com/mathics/Mathics/pull/695/commits/3609988e16c4709297bd75b676823bb767e3f050#diff-c53f701d935994cfef35be4b90836f1cR346
Seems that it's not modified by this PR. It might be a bug that appears in the current master branch too. We'd better fix it individually.

**Comment by wolfv** [comment]
@balthild do you have some time to investigate this? I am hoping to make a new release soon (at least on conda-forge).

**Comment by balthild** [comment]
Sure. I've created a new PR: #783

**Comment by wolfv** [comment]
we still need to take care of this one, correct?

**Comment by suhr** [comment]
Yes. Right now worksheet saving does not work.

It would be nice if @balthild updates his PR and fixed remain issues.

**Comment by mmatera** [comment]
@balthild,  @suhr, I do not know if this still makes sense, but in any case, this should be pushed to MathicsDjango. I close this PR here.

**Pull request closed without merging**
