### PR TITLE
Make psutil optional - msys doesn't have

### PR DESCRIPTION
**Pull request by rocky**
.gitignore: Add cygwin DLL

### CODE REVIEW

**Comment by mmatera** [comment]
@rocky, why do you want to remove this dependency?

**Comment by rocky** [comment]
Not remove it per se but make it optional. 

msys doesn't support it.  Although there are other problems with msys, as I test with more OS's I think it better for Mathics to build more places moving mathics core to be more like a library which can be used more kinds of places. 

I am also seeing a situation where the prompt-toolkit in one of the windows environments where prompt-toolkit isn't available but GNU Readline is.  (And down the line then I guess we also need to allow OSX's lineedit  as an alternative. 

I know this is kind of a reversal of my view from before, but as Mathics has grown and we can add projects like mathics-omnibus on the outside to manage packaging pieces, my thoughts here have changed.

In sum at this point I think it better to allow the various pieces to be installed in more minimal environments.

Your thoughts?

**Comment by mmatera** [comment]
@rocky, thanks for the explanation. So, the idea is that if the `psutil` library is not available (like in windows), the Builtins that depend on it do not load, and then we also avoid running the doctests on them, isn't it? The other way we used to handle these optional libraries was to check into the ``apply`` method if they are available, and return `$Failed` if the library is not available, which of course is a problem in doctests.

**Review by mmatera — APPROVED** [review]
LGTM

**Comment by rocky** [comment]
> @rocky, thanks for the explanation. So, the idea is that if the `psutil` library is not available (like in windows), the Builtins that depend on it do not load, and then we also avoid running the doctests on them, isn't it? 

Yes, they don't run doctests. 

> The other way we used to handle these optional libraries was to check into the `apply` method if they are available, and return `$Failed` if the library is not available, which of course is a problem in doctests.

I will keep that in mind. The situation with doctest for me is a little out of control. 

BTW I will be checking to see if the RealDigits tests that are not part of examples can be moved to unit tests to speed this up.

**Pull request merged**
