### PR TITLE
Fixes for working with Django 2.2

### PR DESCRIPTION
**Pull request by mmatera**
I guess it should work now...

### CODE REVIEW

**Comment by GarkGarcia** [comment]
I'm getting the following error when trying to run `mathicsserver` with Djange 2.2:

```
Migrating database /home/pablo/.local/var/mathics/mathics.sqlite
Traceback (most recent call last):
  File "/home/pablo/Documents/Mathics/mathics/manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/pablo/.local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/pablo/.local/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pablo/Documents/Mathics/mathics/web/models.py", line 54, in <module>
    class Worksheet(models.Model):
  File "/home/pablo/Documents/Mathics/mathics/web/models.py", line 57, in Worksheet
    null=True)
TypeError: __init__() missing 1 required positional argument: 'on_delete'
error: failed to create database
```

**Comment by GarkGarcia** [comment]
> I'm getting the following error when trying to run `mathicsserver` with Djange 2.2:
> 
> ```
> Migrating database /home/pablo/.local/var/mathics/mathics.sqlite
> Traceback (most recent call last):
>   File "/home/pablo/Documents/Mathics/mathics/manage.py", line 13, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/pablo/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
>     utility.execute()
>   File "/home/pablo/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
>     django.setup()
>   File "/home/pablo/.local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/home/pablo/.local/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
>     app_config.import_models()
>   File "/home/pablo/.local/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
>     self.models_module = import_module(models_module_name)
>   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/pablo/Documents/Mathics/mathics/web/models.py", line 54, in <module>
>     class Worksheet(models.Model):
>   File "/home/pablo/Documents/Mathics/mathics/web/models.py", line 57, in Worksheet
>     null=True)
> TypeError: __init__() missing 1 required positional argument: 'on_delete'
> error: failed to create database
> ```

I'm sorry, I hadn't pull your branch properly 😅️

After pulling your changes, `mathicsserver` doesn't crash anymore, but I'm experiencing the same issues as before (the main page becomes unreliable and unresponsive). @rocky Could you give it a try?

**Comment by GarkGarcia** [comment]
I've tested in latest stable version of Firefox. I don't have any non-Gecko-based browsers installed to test it further.

**Comment by GarkGarcia** [comment]
Looking at the server logs and at the Firefox network logs, it looks like the server things it has responded to a request while Firefox doesn't think those requests have been served...

The issue seems to be related with the 304 response code (which apparently indicates "I won't send you this stuff because I know you've got it cached locally"). All requests that hang are marked as `304` in the server logs.

**Comment by GarkGarcia** [comment]
The requests that hang tend to be eventually served, but it can take up to 10 minutes!

**Comment by GarkGarcia** [comment]
Anyway, that's all the testing I can do today. I hope this information helps us figure out what is going on. I don't understand how this kind of stuff works, but it looks like the issue has something to do with caching.

**Comment by rocky** [comment]
Thanks! This information does help a lot.

I need some dedicated time to focus on stuff like this, so this weekend or next is probably when I'll have a chance to really focus on something like this.

**Comment by mmatera** [comment]
It is funny: I tested it on my computer using django 2.2.16 and I didn't see any of these behaviors... It would be nice to have an independent way to check the django interface...

**Comment by suhr** [comment]
Can we disable caching for django to get rid of 304?

**Comment by suhr** [comment]
https://stackoverflow.com/questions/2730274/how-to-prevent-http-304-in-django-test-server

**Comment by GarkGarcia** [comment]
@mmatera You also forgot to replace `MIDDLEWARE_CLASSES` with `MIDDLEWARE` (see https://stackoverflow.com/a/49481923). Can I push a commit to your branch to fix this?

**Comment by GarkGarcia** [comment]
> Can we disable caching for django to get rid of 304?

I don't think this is a good idea in the long-run... That mean more work for server that run Mathics.

> https://stackoverflow.com/questions/2730274/how-to-prevent-http-304-in-django-test-server

That's really interesting. Running the server in a different port fixes the issues for me, so it looks like the error is related to caching indeed.

**Comment by GarkGarcia** [comment]
> It is funny: I tested it on my computer using django 2.2.16 and I didn't see any of these behaviors... It would be nice to have an independent way to check the django interface...

I've updated to Django 2.2.16 for testing and I still experience the same problems. What browser do you use? Also, what's your operating system?

**Comment by suhr** [comment]
> That mean more work for server that run Mathics.

Yes, but the server is usually local and there's only one user. So it make sense as a dirty fix.

**Comment by mmatera** [comment]
> > It is funny: I tested it on my computer using django 2.2.16 and I didn't see any of these behaviors... It would be nice to have an independent way to check the django interface...
> 
> I've updated to Django 2.2.16 for testing and I still experience the same problems. What browser do you use? Also, what's your operating system?

About the changes, go ahead. I guess I will not have time until the weekend to look at it. In my case, I am working on Ubuntu 20.04, with a miniconda as pypy3 interpreter and firefox 81.0 (64 bits) as a browser.

**Comment by GarkGarcia** [comment]
> About the changes, go ahead.

Thanks! 

> In my case, I am working on Ubuntu 20.04, with a miniconda as pypy3 interpreter and firefox 81.0 (64 bits) as a browser.

That's very weird, your setup is similar to mine, although I don't use miniconda and pypy. Maybe it's CPython thing? That doesn't make much sense to me.

> Running the server in a different port fixes the issues for me, so it looks like the error is related to caching indeed.

This is the weirdest part to me, why would running the server on a different port change anything. It runs smoothly in localhost:8001 but not in localhost:8000

**Comment by GarkGarcia** [comment]
> This is the weirdest part to me, why would running the server on a different port change anything. It runs smoothly in localhost:8001 but not in localhost:8000

Actually, it looks like the port doesn't really change anything. The difference is that I used `python3 mathics/manage.py runserver 8001` to run the server on `localhost:8001` instead of `localhost:8000`. Running `python3 mathics/manage.py runserver 8000` works fine too...

**Comment by GarkGarcia** [comment]
Maybe we're not initializing something properly in `mathicsserver`...

**Comment by GarkGarcia** [comment]
> It would be nice to have an independent way to check the django interface...

I agree. Not been able to systematically test one of our front-ends is extremely annoying...

**Comment by rocky** [comment]
Building on this PR, @suhr was able to get this working on  Django 3.1, giving up on 2.2.x since that has a multitasking bug. 

So closing this. However, many thanks for adding the test!

**Pull request closed without merging**
