### PR TITLE
Faster startup

### PR DESCRIPTION
**Pull request by poke1024**
A bunch of changes aimed at making Mathics start up faster:
- a `settings` variable named `BENCHMARK_STARTUP` that turns on benchmarking of module import during startup and prints out loading times for each module
- delayed module imports for `natlang` and `manipulate` (the two slowest modules with 0.6s and 0.3s) based on a new tiny mandatory package called `demandimport` that allows lazy `import`s

### CODE REVIEW

**Comment by rocky** [comment]
I started trying the rebase and I am seeing a failure in testing `$IterationLimit`:

```
1452 ( 7): TEST f[x_, 0] := x; f[x_, n_] := f[x + 1, n - 1];
1453 ( 8): TEST Block[{$IterationLimit = 20}, f[0, 100]]
1454 ( 9): TEST ClearAll[f];
1455 (10): TEST ClearAll[f];
1456 (11): TEST f[x_, 0] := x; f[x_, n_] := Module[{y = x + 1}, f[y, n - 1]];
1457 (12): TEST Block[{$IterationLimit = 20}, f[0, 100]]
----------------------------------------------------------------------
Test failed: $IterationLimit in Reference of built-in symbols / Evaluation
Block[{$IterationLimit = 20}, f[0, 100]]
Exception maximum recursion depth exceeded while calling a Python object

Traceback (most recent call last):


File "mathics/core/pattern.py", line 470, in mathics.core.pattern.ExpressionPattern.match_leaf.match_yield
    yield_func(new_vars, items_rest)
  File "mathics/core/pattern.py", line 457, in mathics.core.pattern.ExpressionPattern.match_leaf.leaf_yield
    yield_func(
  File "mathics/core/rules.py", line 39, in mathics.core.rules.BaseRule.apply.yield_match
    new_expression = self.do_replace(expression, vars, options, evaluation)
  File "mathics/core/rules.py", line 124, in mathics.core.rules.BuiltinRule.do_replace
    return self.function(evaluation=evaluation, **vars_noctx)
  File "/nosenet/muffin-src/external-vcs/github/rocky/Mathics/pymathics/mathics/builtin/scoping.py", line 204, in apply
    result = new_expr.evaluate(evaluation)
  File "mathics/core/expression.py", line 862, in mathics.core.expression.Expression.evaluate
    expr, reevaluate = expr.evaluate_next(evaluation)
  File "mathics/core/expression.py", line 984, in mathics.core.expression.Expression.evaluate_next
    result = rule.apply(new, evaluation, fully=False)
  File "mathics/core/rules.py", line 62, in mathics.core.rules.BaseRule.apply
    self.pattern.match(
  File "mathics/core/pattern.py", line 202, in mathics.core.pattern.ExpressionPattern.match
    self.head.match(
  File "mathics/core/pattern.py", line 132, in mathics.core.pattern.AtomPattern.match
    yield_func(vars, None)
  File "mathics/core/pattern.py", line 194, in mathics.core.pattern.ExpressionPattern.match.yield_head
    self.get_pre_choices(
  File "mathics/core/pattern.py", line 318, in mathics.core.pattern.ExpressionPattern.get_pre_choices
    yield_func(vars)
  File "mathics/core/pattern.py", line 179, in mathics.core.pattern.ExpressionPattern.match.yield_choice
    self.match_leaf(
  File "mathics/core/pattern.py", line 477, in mathics.core.pattern.ExpressionPattern.match_leaf
    self.get_wrappings(
  File "mathics/core/pattern.py", line 339, in mathics.core.pattern.ExpressionPattern.get_wrappings
    yield_func(items[0])
  File "mathics/core/pattern.py", line 473, in mathics.core.pattern.ExpressionPattern.match_leaf.yield_wrapping
    leaf.match(match_yield, item, vars, evaluation, fully=True,
  File "mathics/builtin/patterns.py", line 767, in mathics.builtin.patterns.Pattern_.match
    self.pattern.match(yield_func, expression, new_vars, evaluation)
  File "mathics/builtin/patterns.py", line 952, in mathics.builtin.patterns.Blank.match
    yield_func(vars, None)
  File "mathics/core/pattern.py", line 463, in mathics.core.pattern.ExpressionPattern.match_leaf.match_yield
    self.match_leaf(
  File "mathics/core/pattern.py", line 477, in mathics.core.pattern.ExpressionPattern.match_leaf
    self.get_wrappings(
  File "mathics/core/pattern.py", line 339, in mathics.core.pattern.ExpressionPattern.get_wrappings
    yield_func(items[0])
  File "mathics/core/pattern.py", line 473, in mathics.core.pattern.ExpressionPattern.match_leaf.yield_wrapping
    leaf.match(match_yield, item, vars, evaluation, fully=True,
  File "mathics/builtin/patterns.py", line 767, in mathics.builtin.patterns.Pattern_.match
    self.pattern.match(yield_func, expression, new_vars, evaluation)
  File "mathics/builtin/patterns.py", line 952, in mathics.builtin.patterns.Blank.match
    yield_func(vars, None)
```

May have to break this one up into smaller commits. I think at least adding the Benchmarking would be useful.

**Comment by mmatera** [comment]
Again, if we can work out the pymathics modularization, this PR would be outdated.

**Comment by rocky** [comment]
> Again, if we can work out the pymathics modularization, this PR would be outdated.

I don't think so. The first commit adds benchmarking to see which modules take the most time. So that is useful in of itself to understand which things might be moved to loadable modules. 

Although both are glorified Python imports, this is more lightweight. It may turn out that we delay import of certain BuiltIn functions because they slow down loading. 

There strong case for the separate modules as PyPi packages so that package dependencies especially the ones that introduce packages and libraries needed outside of Python, can be isolated. 

If the package represents something that isn't normally part of Mathematica, then it's fine to have it loaded manually instead of  hard-coding module names into Mathics.

**Comment by rocky** [comment]
I've looked more at this, and alas, the use of the [demandimport](https://pypi.org/project/demandimport/) package might not be advisable.

On modern Python 3.6+ you'll get a deprecation warning because this module uses `imp` instead of `importlib` and the use of that is for `find_module()` [which doesn't have a direct equivalent in importlib](https://stackoverflow.com/questions/35288021/what-is-the-equivalent-of-imp-find-module-in-importlib). 

It is possible and even likely that Python's native import has improved, since this is key to Python's performance. So if this `demandlib` is seems little used and there is little activity on it, this may be why.

That said, the first two commits which add the ability to bemchark module loading and use pkgutil instead of importlib, may be useful to keep

**Comment by mmatera** [comment]
Yes, maybe this would be more suitable for our mathics3 repository. I just look to merge this with the current master, rebase, and check errors....

**Comment by rocky** [comment]
Just ran a timing test on Python 3.7: 

```
import took 1.2 s:
    manipulate 0.329808
    plot 0.316342
    quantities 0.278026
    arithmetic 0.144492
    xmlformat 0.067233
    graphics3d 0.017286
    datentime 0.007003
    graphics 0.006026
    importexport 0.003843
    structure 0.003755
```

Note natlang has been off-loaded to an as-yet-to-be done separate python mathics module. 

1.2 seconds while not ideal is probably tolerable for now. 

While adding a `BENCHMARK_SETUP` setting is interesting, if it is to be done in the furture given that we aren't going to lazyload will be probably some other way.

**Pull request closed without merging**
