### PR TITLE
evaluating the iterator argument before evaluating the iteration func…

### PR DESCRIPTION
**Pull request by mmatera**
This should fix the issue #960 with Table and other iterator functions (like Sum). The issue was due to the lack of evaluation of the iterator argument before the method was chosen.

### CODE REVIEW

**Review by rocky — APPROVED** [review]
Wow - that was fast! Thanks! 

I wonder if a a py.test in the same fashion as that [`test_evaluation.py`](https://github.com/sealemar/Mathics/blob/master/test/test_evaluation.py) mentioned with respect to the orderless "or" can be written?

**Comment by mmatera** [comment]
> Wow - that was fast! Thanks!
> 
> I wonder if a a py.test in the same fashion as that [`test_evaluation.py`](https://github.com/sealemar/Mathics/blob/master/test/test_evaluation.py) mentioned with respect to the orderless "or" can be written?

Do you mean for Iterators?

**Comment by rocky** [comment]
> > Wow - that was fast! Thanks!
> > I wonder if a a py.test in the same fashion as that [`test_evaluation.py`](https://github.com/sealemar/Mathics/blob/master/test/test_evaluation.py) mentioned with respect to the orderless "or" can be written?
> 
> Do you mean for Iterators?

Yes for the iterators. Is this possible?

**Comment by mmatera** [comment]
> > > Wow - that was fast! Thanks!
> > > I wonder if a a py.test in the same fashion as that [`test_evaluation.py`](https://github.com/sealemar/Mathics/blob/master/test/test_evaluation.py) mentioned with respect to the orderless "or" can be written?
> > 
> > 
> > Do you mean for Iterators?
> 
> Yes for the iterators. Is this possible?

I guess so... The @redcabin  tests would work? Something
s={1,2,3};Table[F[x],{x,s}]

and 
s={x,1,10};Table[F[x],s]
?
(BTW, I am fixing this second too now)

**Review by rocky — APPROVED** [review]
Wow this is really fantastic! Thanks!

**Pull request merged**
