### PR TITLE
adding lots of tests for comparison

### PR DESCRIPTION
**Pull request by mmatera**
@rocky , OK: you asked for tests, here you have tests :)

### CODE REVIEW

**Comment by rocky** [comment]
@mmatera  Thanks! This helps a _lot_. I will look over and addresss this over the upcoming weekend.

**Comment by mmatera** [comment]
> @mmatera Thanks! This helps a _lot_. I will look over and addresss this over the upcoming weekend.

I plan also to add the same tests, but  for inequalities

**Comment by rocky** [comment]
@mmatera not that by issuing `git rebsae master` in this branch we went from 9 files changed to 4.

**Comment by mmatera** [comment]
> @mmatera not that by issuing `git rebsae master` in this branch we went from 9 files changed to 4.

I made a push --force on this branch, sorry. Is it possible to undo that? Otherwise, please push your local branch again, and then I merge it with my local branch

**Comment by rocky** [comment]
> > @mmatera not that by issuing `git rebsae master` in this branch we went from 9 files changed to 4.
> 
> I made a push --force on this branch, sorry. Is it possible to undo that? Otherwise, please push your local branch again, and then I merge it with my local branch

No problem. For pushed.  Does it make sense why I suggest the rebase over the merge?

**Comment by mmatera** [comment]
@rocky, in this branch I made some changes in test/help.py   to avoid some problems in the comparison of the expected and obtained results. The idea is that the  output is passed through a `ToString`, and then converted to a Python string, while  the expected is stated in the form of a string. This probably implies making changes on the other tests.

**Comment by mmatera** [comment]
> > > @mmatera not that by issuing `git rebsae master` in this branch we went from 9 files changed to 4.
> > 
> > 
> > I made a push --force on this branch, sorry. Is it possible to undo that? Otherwise, please push your local branch again, and then I merge it with my local branch
> 
> No problem. For pushed. Does it make sense why I suggest the rebase over the merge?

OK, what I did is a merge in this branch from master.  From which commit should I do a rebase?

**Comment by rocky** [comment]
> > > > @mmatera not that by issuing `git rebsae master` in this branch we went from 9 files changed to 4.
> > > 
> > > 
> > > I made a push --force on this branch, sorry. Is it possible to undo that? Otherwise, please push your local branch again, and then I merge it with my local branch
> > 
> > 
> > No problem. For pushed. Does it make sense why I suggest the rebase over the merge?
> 
> OK, what I did is a merge in this branch from master. From which commit should I do a rebase?

This is the process I did in order to try to remove duplicate changes to get a smaller set of changes to work with:

```
$ git checkout master
$ git pull origin HEAD
$ git checkout extensecmptests
$ git rebase master
```

Here is how you can get the this branch as it is now saving your existing branch.

```
$ git checkout extensecmptests
$ git checkout -b extensecmptests-save # this saves the existing branch
$ git checkout master
$ git branch -d extensecmptests  # may need -D instead of -d
$ git fetch 
$ git checkout extensecmptests
```

**Comment by mmatera** [comment]
Well, here is the rebase. Also, I marked the non-working tests to be skipped. However, there are still a couple of doctests that are failing. I think that the bests would be to merge this branch after everything get fixed...

**Comment by mmatera** [comment]
@rocky: I am splitting these cases with this ugly framework because I want to understand the logic and where things go wrong. When I finish, I will try to comment line by line,  and then, we can see how to improve this code.

**Comment by mmatera** [comment]
I close this in favor of #1209

**Pull request closed without merging**
