### PR TITLE
Remove System`$Notebooks from settings.m

### PR DESCRIPTION
**Pull request by TiagoCavalcanteTrindade**
Remove System`$Notebooks from settings.m as all front ends already implement it

### CODE REVIEW

**Review by rocky — CHANGES_REQUESTED** [review]
This was no doubt a TODO item until we got all the setting in place in the other repositories and pushed. 

We should add a test however for the mathics CLI for it settings. You can find a corresponding one over in the mathicsscript project. 

Would you please add the test (adjusting accordingly)?  I suppose we could test that Notebooks is universally false too.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky I added the test, there's a TODO saying that we should do more, but what?

**Comment by rocky** [comment]
> @rocky I added the test, there's a TODO saying that we should do more, but what?

I don't know what you are talking about. Everything now looks fine. Thanks!

**Review by rocky — APPROVED** [review]
LGTM  after CI clears.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky [here](https://github.com/Mathics3/mathicsscript/blob/master/test/test_settings.py#L6) is the FIXME.

**Comment by rocky** [comment]
> @rocky [here](https://github.com/Mathics3/mathicsscript/blob/master/test/test_settings.py#L6) is the FIXME.

@TiagoCavalcanteTrindade  Ah - ok. thanks. Here I just tested that settings were set to _some_ value.  In those cases where we think values will change a bit over time (e.g. if a version number were set) then this is the best thing.

For things like Notebook, we _know_ this will never be the case so that should probably test false explicitly.

For some things, were a value might change like a version but we know the datatype, then we should test on the datatype.

That's the kind of thing I meant.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky ok, I'll do this test.

**Review by rocky — CHANGES_REQUESTED** [review]
The whole test/test_settings.py test I now learn is a mess. (And yes, I was the one who created this out of ignorance).

It should be revised to autoload and at least test the values are defined which means the a value different from the setting name comes back. Possibly with a particular value or a particular type.

**Review by rocky — APPROVED** [review]
It's been a long time coming, but finally! Great work!

**Comment by TiagoCavalcanteTrindade** [comment]
Yes, after a lot of force pushes it's done!

**Pull request merged**
