### PR TITLE
Symbolic comparisions

### LINKED ISSUE #956: Symbolic Min/Max
`Min[E, Pi]` currently does not give a result.

This is what Wolfram gives:

image

`sympy` has inbuilt Min/Max functions that have the same functionality:

```python
>>> Min(E, pi)
E
```

One thing to note tho is that `sympy`'s min/max is pretty slow with large (>1000 element) lists. See sympy/sympy#16249.

### PR DESCRIPTION
**Pull request by weakit**
Closes #956

### CODE REVIEW

**Comment by mmatera** [comment]
It looks nicer, but we need to be careful with how numbers and certain mathics structures handled different in sympy are compared.

**Comment by weakit** [comment]
> It looks nicer, but we need to be careful with how numbers and certain mathics structures handled different in sympy are compared.
Thanks. And yes, I'm working on that.

**Comment by weakit** [comment]
It looks like all the tests have passed. Maybe we can add a few more tests? 
And also could someone help me implement the `General::nord` message? (for when complex numbers are compared)

**Comment by mmatera** [comment]
> It looks like all the tests have passed. Maybe we can add a few more tests?
Great! It would be nice to have more tests if you can think a couple.

> And also could someone help me implement the `General::nord` message? (for when complex numbers are compared)
Regarding the message, you can implement it as an exception, raise it from do_cmp, capture in the different builtins, and raise the message from there.

**Comment by weakit** [comment]
>Regarding the message, you can implement it as an exception, raise it from do_cmp, capture in the different builtins, and raise the message from there.

Thanks! I'll look into that.

**Comment by GarkGarcia** [comment]
@weakit Great work!

**Comment by weakit** [comment]
I couldn't really come up with any more tests. I already added some in my previous commit.
And as for the message, I think I'll tackle that later.

I think this PR can be merged.

**Pull request closed without merging**
