### PR TITLE
Rename `faceColor`

### PR DESCRIPTION
**Pull request by TiagoCavalcanteTrindade**
Rename `faceColor` to `color` (in the JSONfy part of the graphics).  
And uncapitalize the lights' names.

### CODE REVIEW

**Comment by rocky** [comment]
A couple of things here. First this needs to be coordinated with changes on all of the front-end side. (A release is coming up over the weekend so now is not a good time for this.)

As suggested by https://github.com/JerryI/Mathematica-ThreeJS-graphics-engine perhaps we are already doing too much work on the Core side and should offload that the renderer part of the frontend. 

And if that is done, we keep the WL/Mathics names which means keeping the capitalization.

There may be a need or desire to have a lower-level JSON representation which makes the job of the JSON to graphics library job easier.  But still it feels to me that we should still follow WL/Mathics style names where possible.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky so we should capitalize the primitives.

**Comment by rocky** [comment]
> @rocky so we should capitalize the primitives.

Not just captialize them but use the corresponding names as well. If there are things that need to get filled in that obviously will never be part of the graphics description (these are low-level things like a translation function name of a WL concept to a three-js concept), then you get to choose whatever you want and use whatever style you want.

**Comment by rocky** [comment]
Note: Release as promised is underway. The main motivation for this was to address #1452. (And I happen to have time this weekend). This change is API breaking and while useful, needs to be delayed a little.

**Comment by TiagoCavalcanteTrindade** [comment]
Strange, the tests pass locally.

**Pull request closed without merging**
