### PR TITLE
Support for open files from internet

### PR DESCRIPTION
**Pull request by mmatera**
Support to open files from a URL. For example

OpenRead["https://raw.githubusercontent.com/mathics/Mathics/master/README.rst"]

download the content of the mathics'  README.rst, store it in a temporary file, open it, and returns a stream associated with that file.

The mechanism could be improved in the future...

### CODE REVIEW

**Comment by rocky** [comment]
Nice!. I have a feeling this will help in [import@ as well](https://github.com/jkuczm/MathematicaCellsToTeX#compatibility).

**Comment by mmatera** [comment]
I thought it could be useful for instance, to load mma packages published online, or to load data from public repositories...

**Comment by rocky** [comment]
> I thought it could be useful for instance, to load mma packages published online, or to load data from public repositories...

Yes! And establishing a easy path to this for example to hook into http://packagedata.net/ I think is important to the success of the growth of this project.

**Comment by rocky** [comment]
@mmatera  As a follow-on would you consider covering `import@`?

**Pull request merged**
