### PR TITLE
Created some tests for direct evaluation in mathics

### PR DESCRIPTION
**Pull request by wolfv**
Hi, 

I added a unit test for direct evaluation in a 'virtual' Mathics shell. I think this will make it handy to write some tests for different functions, especially with list slicing and flattening in mind. 

Wolf

### CODE REVIEW

**Comment by wolfv** [comment]
Ah, just realized that the docstrings are test cases too. Cool! 
Though, this might make sense anyways as it would hide really strange tests from the user.

**Comment by wolfv** [comment]
Ah, just realized that the docstrings are test cases too. Cool! 
Though, this might make sense anyways as it would hide really strange tests from the user.

**Comment by sn6uv** [comment]
That's right, lines in the docstrings beginning with `>>` are part of the docs and also used as test cases. Additionally, lines beginning with `#>` are silent tests.

For tests that are specific to a single function we try to put them in the docstrings for that function definition.

The `tests/` directory is mostly for tests that aren't specific to a single function. For example testing of the parser or the command line interface (we don't have any tests for the web interface yet).

**Comment by sn6uv** [comment]
These are are all good tests. Also, it's great to see you beginning to play with the Mathics internals

**Comment by wolfv** [comment]
Great to know! Cool invention with the tests in the comments :)

**Comment by wolfv** [comment]
It's really fun to create some functions for Mathics, by the way.

**Pull request closed without merging**
