### PR TITLE
Remove implementation details from user-facing documentation

### PR DESCRIPTION
**Pull request by GarkGarcia**
This is a follow up to https://github.com/mathics/Mathics/issues/957#issuecomment-706743180. I moved all notes about implementation details to the wiki and removed the _Implementation_ section from the PDF documentation. See https://github.com/mathics/Mathics/wiki/Developing, https://github.com/mathics/Mathics/wiki/Documentation-and-tests, https://github.com/mathics/Mathics/wiki/Documentation-markup, https://github.com/mathics/Mathics/wiki/Classes, https://github.com/mathics/Mathics/wiki/Adding-builtin-symbols.

### CODE REVIEW

**Review by rocky — APPROVED** [review]
Comments are mostly about the wiki, not this. 

https://github.com/mathics/Mathics/wiki/Classes has a broken link to a png that points into a file removed in this PR. Probably the png should be moved into the wiki. 

* https://github.com/mathics/Mathics/wiki/Integrated-Documentation-and-Testing-setup
* https://github.com/mathics/Mathics/wiki/Documentation-and-tests and
* https://github.com/mathics/Mathics/wiki/Documentation-markup

all have overlaps in some way. Not sure what should be done about that.

**Comment by GarkGarcia** [comment]
> https://github.com/mathics/Mathics/wiki/Classes has a broken link to a png that points into a file removed in this PR

The file was added in this PR. My idea is that as soon as this PR is merged the link will start working.

>     * https://github.com/mathics/Mathics/wiki/Integrated-Documentation-and-Testing-setup
> 
>     * https://github.com/mathics/Mathics/wiki/Documentation-and-tests and
> 
>     * https://github.com/mathics/Mathics/wiki/Documentation-markup
> 
> 
> all have overlaps in some way. Not sure what should be done about that.

Indeed, and there's a lot of overlap in previously existing sections of the wiki too (such as https://github.com/mathics/Mathics/wiki/Building-the-documentation and https://github.com/mathics/Mathics/wiki/Documentation-and-tests). All I did was to dump the contents of the PDF in the wiki (so that the information isn't lost), we should refactors things there now.

**Comment by rocky** [comment]
> > https://github.com/mathics/Mathics/wiki/Classes has a broken link to a png that points into a file removed in this PR
> 
> The file was added in this PR. My idea is that as soon as this PR is merged the link will start working.
> 
> > ```
> > * https://github.com/mathics/Mathics/wiki/Integrated-Documentation-and-Testing-setup
> > 
> > * https://github.com/mathics/Mathics/wiki/Documentation-and-tests and
> > 
> > * https://github.com/mathics/Mathics/wiki/Documentation-markup
> > ```
> > 
> > 
> > all have overlaps in some way. Not sure what should be done about that.
> 
> Indeed, and there's a lot of overlap with previously existing sections of the wiki too (such as https://github.com/mathics/Mathics/wiki/Building-the-documentation and https://github.com/mathics/Mathics/wiki/Documentation-and-tests). All I did was to dump the contents of the PDF in the wiki (so that the information isn't lost), we should refactors things there now.

What is weird about having this in the github repository is that this PNG is derived from `mathics/doc/documentation/images/classes.dia` 

I think there is a way to add just the PNG to the wiki and not the git repository which has a way of regnerating this I think.

**Comment by GarkGarcia** [comment]
> I think there is a way to add just the PNG to the wiki and not the git repository which has a way of regnerating this I think.

There's a way to place the image directly on the wiki, but it wouldn't be automatically updated (which I'm not too worried about).

Anyway, the tests are passing (the doc-tests are failing, but they failed in the last commit to master too), any reason to not merge this?

**Comment by GarkGarcia** [comment]
> What is weird about having this in the github repository is that this PNG is derived from mathics/doc/documentation/images/classes.dia

I agree, the current scheme is pretty weird. I'm not too worried about this thought, as I plan to refactor the wiki in the next few days.

**Comment by rocky** [comment]
> > What is weird about having this in the github repository is that this PNG is derived from mathics/doc/documentation/images/classes.dia
> 
> I agree, the current scheme is pretty weird. I'm not too worried about this thought, as I plan to refactor the wiki in the next few days.

If you want to go big, butter would be to set up a separte developer doc in the git repo that uses Sphinx and  that we can host on https://readthedocs.org

However just organizing the Wiki better would be a win too. So thanks for doing this.

**Comment by GarkGarcia** [comment]
> However just organizing the Wiki better would be a win too. So thanks for doing this.

I think I'll start by doing this. It seems more appropriate to implement the Sphinx thing when we're redesigning the documentation system altogether.

**Comment by rocky** [comment]
> > However just organizing the Wiki better would be a win too. So thanks for doing this.
> 
> I think I'll start by doing this. It seems more appropriate to implement the Sphinx thing when we're redesigning the documentation system altogether.

Awesome! 

Down the line there's probably a sphinx way to recreate the PNG diagram for that dia diagram so that if that changes the developer doc PNG gets updated automatically. 

But that is way way way down the line.

**Pull request merged**
