### PR TITLE
Importatmodule

### PR DESCRIPTION
**Pull request by mmatera**
I found the bug that produces different behaviour between `Import@url `and `Get[url]` for loading modules, and I fix it. 

However, when I try with `Import@"https://raw.githubusercontent.com/jkuczm/MathematicaCellsToTeX/master/NoInstall.m"`
(or `Get["https://raw.githubusercontent.com/jkuczm/MathematicaCellsToTeX/master/NoInstall.m]`) mathics finishes with the  exception that I copy bellow. In any case, the pourpose of this branch I guess is achieved. What we need to dig a little bit is why this module raise such exception.
```
ClearAttributes::sym: Argument `* at position 1 is expected to be a symbol.

Syntax::sntufn: Unknown unicode longname "IndentingNewLine" (line 66 of "/tmp/tmp2ep3fvez.m").

Syntax::sntufn: Unknown unicode longname "IndentingNewLine" (line 283 of "/tmp/tmp2ep3fvez.m").

Traceback (most recent call last):

  File "/opt/miniconda3/envs/mathics/bin/mathics", line 33, in <module>
    sys.exit(load_entry_point('Mathics', 'console_scripts', 'mathics')())
  File "/home/mauricio/Projects/mymathics/mathics/main.py", line 303, in main
    result = evaluation.parse_evaluate(expr, timeout=settings.TIMEOUT)
  File "/home/mauricio/Projects/mymathics/mathics/core/evaluation.py", line 222, in parse_evaluate
    return self.evaluate(expr, timeout)
  File "/home/mauricio/Projects/mymathics/mathics/core/evaluation.py", line 291, in evaluate
    result = run_with_timeout_and_stack(evaluate, timeout)
  File "/home/mauricio/Projects/mymathics/mathics/core/evaluation.py", line 95, in run_with_timeout_and_stack
    return request()
  File "/home/mauricio/Projects/mymathics/mathics/core/evaluation.py", line 269, in evaluate
    result = query.evaluate(self)
  File "/home/mauricio/Projects/mymathics/mathics/core/expression.py", line 1094, in evaluate
    expr, reevaluate = expr.evaluate_next(evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/core/expression.py", line 1222, in evaluate_next
    result = rule.apply(new, evaluation, fully=False)
  File "/home/mauricio/Projects/mymathics/mathics/core/rules.py", line 63, in apply
    self.pattern.match(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 238, in match
    self.head.match(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 137, in match
    yield_func(vars, None)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 230, in yield_head
    self.get_pre_choices(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 358, in get_pre_choices
    yield_func(vars)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 215, in yield_choice
    self.match_leaf(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 517, in match_leaf
    self.get_wrappings(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 379, in get_wrappings
    yield_func(items[0])
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 513, in yield_wrapping
    leaf.match(match_yield, item, vars, evaluation, fully=True,
  File "/home/mauricio/Projects/mymathics/mathics/builtin/patterns.py", line 770, in match
    self.pattern.match(yield_func, expression, new_vars, evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/patterns.py", line 955, in match
    yield_func(vars, None)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 503, in match_yield
    self.match_leaf(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 517, in match_leaf
    self.get_wrappings(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 390, in get_wrappings
    yield_func(sequence)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 513, in yield_wrapping
    leaf.match(match_yield, item, vars, evaluation, fully=True,
  File "/home/mauricio/Projects/mymathics/mathics/builtin/patterns.py", line 1332, in match
    yield_func(new_vars, None)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 510, in match_yield
    yield_func(new_vars, items_rest)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 497, in leaf_yield
    yield_func(
  File "/home/mauricio/Projects/mymathics/mathics/core/rules.py", line 40, in yield_match
    new_expression = self.do_replace(expression, vars, options, evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/core/rules.py", line 126, in do_replace
    return self.function(
  File "/home/mauricio/Projects/mymathics/mathics/builtin/importexport.py", line 536, in apply
    return self.apply_elements(filename, Expression('List'), evaluation, options)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/importexport.py", line 562, in apply_elements
    return self._import(findfile, determine_filetype, elements, evaluation, options)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/importexport.py", line 667, in _import
    defaults = get_results(default_function, findfile)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/importexport.py", line 634, in get_results
    tmp = Expression(tmp_function, findfile, *joined_options).evaluate(evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/core/expression.py", line 1094, in evaluate
    expr, reevaluate = expr.evaluate_next(evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/core/expression.py", line 1222, in evaluate_next
    result = rule.apply(new, evaluation, fully=False)
  File "/home/mauricio/Projects/mymathics/mathics/core/rules.py", line 63, in apply
    self.pattern.match(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 238, in match
    self.head.match(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 137, in match
    yield_func(vars, None)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 230, in yield_head
    self.get_pre_choices(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 358, in get_pre_choices
    yield_func(vars)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 215, in yield_choice
    self.match_leaf(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 517, in match_leaf
    self.get_wrappings(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 379, in get_wrappings
    yield_func(items[0])
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 513, in yield_wrapping
    leaf.match(match_yield, item, vars, evaluation, fully=True,
  File "/home/mauricio/Projects/mymathics/mathics/builtin/patterns.py", line 770, in match
    self.pattern.match(yield_func, expression, new_vars, evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/patterns.py", line 953, in match
    yield_func(vars, None)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 510, in match_yield
    yield_func(new_vars, items_rest)
  File "/home/mauricio/Projects/mymathics/mathics/core/rules.py", line 40, in yield_match
    new_expression = self.do_replace(expression, vars, options, evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/core/rules.py", line 129, in do_replace
    return self.function(evaluation=evaluation, **vars_noctx)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/files.py", line 2154, in apply
    result = query.evaluate(evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/core/expression.py", line 1094, in evaluate
    expr, reevaluate = expr.evaluate_next(evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/core/expression.py", line 1222, in evaluate_next
    result = rule.apply(new, evaluation, fully=False)
  File "/home/mauricio/Projects/mymathics/mathics/core/rules.py", line 63, in apply
    self.pattern.match(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 238, in match
    self.head.match(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 137, in match
    yield_func(vars, None)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 230, in yield_head
    self.get_pre_choices(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 358, in get_pre_choices
    yield_func(vars)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 215, in yield_choice
    self.match_leaf(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 517, in match_leaf
    self.get_wrappings(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 390, in get_wrappings
    yield_func(sequence)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 513, in yield_wrapping
    leaf.match(match_yield, item, vars, evaluation, fully=True,
  File "/home/mauricio/Projects/mymathics/mathics/builtin/patterns.py", line 770, in match
    self.pattern.match(yield_func, expression, new_vars, evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/patterns.py", line 1066, in match
    yield_func(vars, None)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 510, in match_yield
    yield_func(new_vars, items_rest)
  File "/home/mauricio/Projects/mymathics/mathics/core/rules.py", line 40, in yield_match
    new_expression = self.do_replace(expression, vars, options, evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/core/rules.py", line 129, in do_replace
    return self.function(evaluation=evaluation, **vars_noctx)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/control.py", line 86, in apply
    result = expr.evaluate(evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/core/expression.py", line 1094, in evaluate
    expr, reevaluate = expr.evaluate_next(evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/core/expression.py", line 1222, in evaluate_next
    result = rule.apply(new, evaluation, fully=False)
  File "/home/mauricio/Projects/mymathics/mathics/core/rules.py", line 63, in apply
    self.pattern.match(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 238, in match
    self.head.match(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 137, in match
    yield_func(vars, None)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 230, in yield_head
    self.get_pre_choices(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 358, in get_pre_choices
    yield_func(vars)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 215, in yield_choice
    self.match_leaf(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 517, in match_leaf
    self.get_wrappings(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 379, in get_wrappings
    yield_func(items[0])
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 513, in yield_wrapping
    leaf.match(match_yield, item, vars, evaluation, fully=True,
  File "/home/mauricio/Projects/mymathics/mathics/builtin/patterns.py", line 770, in match
    self.pattern.match(yield_func, expression, new_vars, evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/patterns.py", line 955, in match
    yield_func(vars, None)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 503, in match_yield
    self.match_leaf(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 517, in match_leaf
    self.get_wrappings(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 390, in get_wrappings
    yield_func(sequence)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 513, in yield_wrapping
    leaf.match(match_yield, item, vars, evaluation, fully=True,
  File "/home/mauricio/Projects/mymathics/mathics/builtin/patterns.py", line 1332, in match
    yield_func(new_vars, None)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 510, in match_yield
    yield_func(new_vars, items_rest)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 497, in leaf_yield
    yield_func(
  File "/home/mauricio/Projects/mymathics/mathics/core/rules.py", line 40, in yield_match
    new_expression = self.do_replace(expression, vars, options, evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/core/rules.py", line 126, in do_replace
    return self.function(
  File "/home/mauricio/Projects/mymathics/mathics/builtin/importexport.py", line 536, in apply
    return self.apply_elements(filename, Expression('List'), evaluation, options)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/importexport.py", line 562, in apply_elements
    return self._import(findfile, determine_filetype, elements, evaluation, options)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/importexport.py", line 667, in _import
    defaults = get_results(default_function, findfile)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/importexport.py", line 634, in get_results
    tmp = Expression(tmp_function, findfile, *joined_options).evaluate(evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/core/expression.py", line 1094, in evaluate
    expr, reevaluate = expr.evaluate_next(evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/core/expression.py", line 1222, in evaluate_next
    result = rule.apply(new, evaluation, fully=False)
  File "/home/mauricio/Projects/mymathics/mathics/core/rules.py", line 63, in apply
    self.pattern.match(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 238, in match
    self.head.match(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 137, in match
    yield_func(vars, None)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 230, in yield_head
    self.get_pre_choices(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 358, in get_pre_choices
    yield_func(vars)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 215, in yield_choice
    self.match_leaf(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 517, in match_leaf
    self.get_wrappings(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 379, in get_wrappings
    yield_func(items[0])
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 513, in yield_wrapping
    leaf.match(match_yield, item, vars, evaluation, fully=True,
  File "/home/mauricio/Projects/mymathics/mathics/builtin/patterns.py", line 770, in match
    self.pattern.match(yield_func, expression, new_vars, evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/patterns.py", line 953, in match
    yield_func(vars, None)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 510, in match_yield
    yield_func(new_vars, items_rest)
  File "/home/mauricio/Projects/mymathics/mathics/core/rules.py", line 40, in yield_match
    new_expression = self.do_replace(expression, vars, options, evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/core/rules.py", line 129, in do_replace
    return self.function(evaluation=evaluation, **vars_noctx)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/files.py", line 2154, in apply
    result = query.evaluate(evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/core/expression.py", line 1094, in evaluate
    expr, reevaluate = expr.evaluate_next(evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/core/expression.py", line 1222, in evaluate_next
    result = rule.apply(new, evaluation, fully=False)
  File "/home/mauricio/Projects/mymathics/mathics/core/rules.py", line 63, in apply
    self.pattern.match(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 238, in match
    self.head.match(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 137, in match
    yield_func(vars, None)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 230, in yield_head
    self.get_pre_choices(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 358, in get_pre_choices
    yield_func(vars)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 215, in yield_choice
    self.match_leaf(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 517, in match_leaf
    self.get_wrappings(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 379, in get_wrappings
    yield_func(items[0])
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 513, in yield_wrapping
    leaf.match(match_yield, item, vars, evaluation, fully=True,
  File "/home/mauricio/Projects/mymathics/mathics/builtin/patterns.py", line 770, in match
    self.pattern.match(yield_func, expression, new_vars, evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/patterns.py", line 955, in match
    yield_func(vars, None)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 503, in match_yield
    self.match_leaf(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 517, in match_leaf
    self.get_wrappings(
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 379, in get_wrappings
    yield_func(items[0])
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 513, in yield_wrapping
    leaf.match(match_yield, item, vars, evaluation, fully=True,
  File "/home/mauricio/Projects/mymathics/mathics/builtin/patterns.py", line 770, in match
    self.pattern.match(yield_func, expression, new_vars, evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/patterns.py", line 955, in match
    yield_func(vars, None)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 510, in match_yield
    yield_func(new_vars, items_rest)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 497, in leaf_yield
    yield_func(
  File "/home/mauricio/Projects/mymathics/mathics/core/rules.py", line 40, in yield_match
    new_expression = self.do_replace(expression, vars, options, evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/core/rules.py", line 129, in do_replace
    return self.function(evaluation=evaluation, **vars_noctx)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/assignment.py", line 412, in apply
    self.assign(lhs, rhs, evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/assignment.py", line 331, in assign
    return self.assign_elementary(lhs, rhs, evaluation)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/assignment.py", line 264, in assign_elementary
    rule = Rule(lhs, rhs)
  File "/home/mauricio/Projects/mymathics/mathics/core/rules.py", line 79, in __init__
    super(Rule, self).__init__(pattern, system=system)
  File "/home/mauricio/Projects/mymathics/mathics/core/rules.py", line 18, in __init__
    self.pattern = Pattern.create(pattern)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 31, in Pattern_create
    return ExpressionPattern(expr)
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 362, in __init__
    self.leaves = [Pattern.create(leaf) for leaf in expr.leaves]
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 362, in <listcomp>
    self.leaves = [Pattern.create(leaf) for leaf in expr.leaves]
  File "/home/mauricio/Projects/mymathics/mathics/core/pattern.py", line 27, in Pattern_create
    return pattern_object(expr)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/base.py", line 316, in __new__
    instance.init(*args, **kwargs)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/patterns.py", line 1123, in init
    self.error('range', 2, expr)
  File "/home/mauricio/Projects/mymathics/mathics/builtin/base.py", line 561, in error
    raise PatternError(self.get_name(), tag, *args)
mathics.builtin.base.PatternError: ('System`Repeated', 'range', 2, <Expression: System`Repeated[System`Blank[], System`List[0, 1]]>)
```

### CODE REVIEW

**Review by GarkGarcia — APPROVED** [review]

**Review by rocky — APPROVED** [review]
The basic proble is that the CellsToTeX file proper doesn't load and we are hitting a parsing error in Mathics. 

I've added a number of the missing Unicode symbols from FoxySheep, but there's more that needs to be done. This can be done in a separate PR since this is really a separate problem - the import part seems to work. 

I'll be adding issues for some of the issues found.

**Comment by mmatera** [comment]
Shall I close the merged branches with small fixes?

**Comment by rocky** [comment]
Looks like you have. If not do whatever needs to be done. In general if I don't respond in a timely fashion just move ahead (assuming things aren't broken as I think was the case).

**Comment by mmatera** [comment]
No, I mean, to delete de merged branches.

**Comment by rocky** [comment]
Ok. Deleted. In the future if you want to delete if you think it's not necessary, that's okay. I'll have a local copy of course.

**Pull request merged**
