### PR TITLE
Update the links in the documentation to point to mathics.org

### PR DESCRIPTION
**Pull request by GarkGarcia**
Update the links in the documentation to point to mathics.org instead of mathics.github.io

### CODE REVIEW

**Comment by GarkGarcia** [comment]
@mathics/maintainers Any objections?

**Comment by poeschko** [comment]
Seems good! My only comment is that there are a few places where it's still using http that could be changed to https.

**Comment by GarkGarcia** [comment]
> Seems good! My only comment is that there are a few places where it's still using http that could be changed to https.

Good idea!

**Comment by rocky** [comment]
I need commit de2e4bdc in order to make a new docker image - a bootstrap problem.

**Comment by GarkGarcia** [comment]
@rocky I think I'm done. Unless there's something you'd like to change, this is no longer WIP.

**Comment by rocky** [comment]
Sorry, my bad. I had the wrong branch. I'm updating docker info.

**Pull request merged**
