### PR TITLE
Implementation of StringReverse[]

### PR DESCRIPTION
**Pull request by Piruzzolo**
It does not work on nested lists, for now

### CODE REVIEW

**Comment by sn6uv** [comment]
A good start.

Two small bits of feedback:

- Nested lists are tricky to deal with, however, `StringReverse` should have the `Listable` attribute. Once you add it they should be handled for free and you only need to implement the single string case. There some examples on how to specify attributes; try a search for `Listable`, I like e.g. `git grep Listable`. 
- The tests Travis CI tests are failing, if you take a look at the log, e.g. [here](https://travis-ci.org/mathics/Mathics/jobs/127087165), you can see that it's the examples you added. You can also run the tests locally (so you don't have to wait for travis) e.g. `python mathics/test.py -s StringReverse`.

We have a guide for contributing https://github.com/mathics/Mathics/wiki/Contributing but it looks like you figured most of it out on your own.

**Comment by Piruzzolo** [comment]
Seems there are some problems with Travis. The command `python mathics/test.py -s StringReverse` exits normally on my machine (with python 2.7). May I forget to edit some other file?

**Comment by sn6uv** [comment]
Looks like you didn't commit the changes, 4b3cfee just added windows line endings (CLRF). 

Here's the failed tests https://travis-ci.org/mathics/Mathics/jobs/127116726#L4692.

**Comment by sn6uv** [comment]
@Piruzzolo How's everything going? Did you get stuck on something specific I can help you with?

**Comment by Piruzzolo** [comment]
I've just enabled Travis for my fork, but I've no idea what's the problem. Meanwhile, I'm implementing a couple of other functions (QRDecomposition, Mean, Variance, StandardDeviation). Can you decypher my travis log?

**Comment by sn6uv** [comment]
A word on how to interpret the logs. If you scroll to the end:

3205 Tests for 615 built-in symbols, 3203 passed, 2 failed, 0 skipped.
Failed:
  - StringReverse in Reference of built-in symbols / String functions

and then scrolling up a little we find the failures:


2407. TEST StringReverse["hello world"]
----------------------------------------------------------------------
Test failed: StringReverse in Reference of built-in symbols / String functions
StringReverse["hello world"]
Result: hello world
Wanted: "dlrow olleh"

2408. TEST StringReverse[{"cat", "mouse", "lion"}]
----------------------------------------------------------------------
Test failed: StringReverse in Reference of built-in symbols / String functions
StringReverse[{"cat", "mouse", "lion"}]
Result: {tac, esuom, noil}
Wanted: {"tac", "esuom", "noil"}

It looks like you haven't comitted and pushed the changes to github. The last thing you comitted just added windows style line endings to strings.py

**Comment by Piruzzolo** [comment]
Will fix, thanks a lot

**Comment by sn6uv** [comment]
Closing this. If you would still like to implement this let me know and I'll reopen.

**Pull request closed without merging**
