### PR TITLE
Flatten

### PR DESCRIPTION
**Pull request by sn6uv**
Implementation of the `Flatten` algorithm.

### CODE REVIEW

**Comment by sn6uv** [comment]
Might not have a chance to finish this till next week. It works currently if the send argument is a list of length one lists of ints e.g. `{{2}, {1}}` but I still need to figure out how to e.g. length > 1 sublists e.g. `{{1, 2}, {3}}` and the other special cases with rules e.g. `{2}` -> ?

@wolfv if you feel like having a go feel free to submit a PR against this branch sn6uv/Flatten, or alternately you can make your own seperate PR entirely

**Comment by wolfv** [comment]
Thats great to hear! Time is not an issue for me :+1:

**Comment by sn6uv** [comment]
Length > 1 sublists are done. I still need to do some error handling (e.g. check that the list arg matches the correct format) and a minor cleanup.

@wolfv I'd appreciate your feedback on this. Would you mind testing it with what you have in #252?

**Comment by wolfv** [comment]
Hi! So far looks great. 

One smallish issue I found is this one: 

`Flatten[a, {2, 1}]`

where it crashes `int object not iterable`. I guess it expects a list, maybe a fix would be to just wrap it?

**Comment by sn6uv** [comment]
@wolfv I've applied that fix, thanks. I'm done tweaking this now.

**Comment by sn6uv** [comment]
I'm planning to merge this soon. @wolfv are there any more issues you can think of?

**Comment by wolfv** [comment]
Looks great!

**Pull request merged**
