### PR TITLE
Unprotect $InstallationDirectory

### PR DESCRIPTION
**Pull request by rocky**
Do any of these also need to be unprotected?:

@mmatera  @GarkGarcia $BaseDirectory $HomeDirectory $InitialDirectory $UserBaseDirectory

### CODE REVIEW

**Comment by rocky** [comment]
Not sure why this is failing because it works when I run locally.

**Comment by mmatera** [comment]
$InstallationDirectory is the place where the Kernel is installed. Why would you like to overwrite it?

**Comment by mmatera** [comment]
@rocky, I do not see why you think that these symbols should be unprotected. In principle, all of them represent fixed places  in the filesystem. Why would you like to overwrite them?

**Comment by rocky** [comment]
This PR was in response to something someone asked for. I can't find the issue or comment, and I think we had decided that this wasn't the right thing to do anyway. 

So closing.

**Pull request closed without merging**
