### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by rocky**
Used wrong markup language syntax.

### CODE REVIEW

**Comment by suhr** [comment]
Should we keep it in rst format, or maybe it's better to convert it to markdown?

**Comment by mmatera** [comment]
We could mention here the possibility of using the iwolfram jupyter interface. I tested it on my machine, and the only problem is that I need to extend the standard timeout of jupyter for launching the kernel because mathics takes a lot to load...

**Comment by GarkGarcia** [comment]
> Should we keep it in rst format, or maybe it's better to convert it to markdown?

I think we should keep using rst for now. We could change that in a later PR.

**Comment by rocky** [comment]
And advantage of rst is that it can be used on PyPI in the description. 

Other than that, I don't have a preference.

**Comment by rocky** [comment]
> We could mention here the possibility of using the iwolfram jupyter interface (maybe marked ad experimental...). I tested it on my machine, and the only problem is that I need to extend the standard timeout of jupyter for launching the kernel because mathics takes a lot to load...

Sure, mark it as experimental. I haven't been able to get iwolfram working yet. I do however plan at some point to spend time to work on it. 

I was/am thinking more strategically in the long run.

**Pull request merged**
