### PR TITLE
Surround string output in double quotes.

### PR DESCRIPTION
**Pull request by rocky**
Add double quotes to string output.

### CODE REVIEW

**Comment by mmatera** [comment]
Wolframscript does not:
```
 In[1]:= "Tengo una vaca Lechera"
 Out[2]= Tengo una vaca Lechera
```

**Comment by rocky** [comment]
Ok. in mathics we will leave them out. 

I think this is not helpful though and I find it confusing. So in mathicsscript I will add an option to be strictly compatible which is off by default. Also mathicsscript and django have the ability to ensure that the font used can be different.

**Comment by axkr** [comment]
>  "Tengo una vaca Lechera"

```
  "Tengo una vaca Lechera" // InputForm
```

and

```
  "Tengo una vaca Lechera" // FullForm
```

printes the double quotes

**Comment by rocky** [comment]
> > "Tengo una vaca Lechera"
> 
> ```
>   "Tengo una vaca Lechera" // InputForm
> ```
> 
> and
> 
> ```
>   "Tengo una vaca Lechera" // FullForm
> ```
> 
> will print the double quotes
> 
> ```
>   "Tengo una vaca Lechera" // OutputForm
> ```
> 
> don't.

Interesting...

**Comment by mmatera** [comment]
For me, both are OK for the basic command-line interface.

**Review by mmatera — APPROVED** [review]
LGTM

**Pull request merged**
